"use client";

/* eslint-disable @next/next/no-html-link-for-pages */
import { useMemo, useState } from "react";
import { PageHeading, StatusBadge } from "@/components/page-heading";
import { demoCustomers } from "@/lib/demo";
import { useDemoOffice } from "@/lib/demo-office";

export default function CustomersPage() {
  const [customers, setCustomers] = useState(demoCustomers);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<(typeof demoCustomers)[number] | null>(null);
  const [status, setStatus] = useState("すべての契約状態");
  const [formOpen, setFormOpen] = useState(false);
  const [detailTab, setDetailTab] = useState("基本情報");
  const { office } = useDemoOffice();
  const filtered = useMemo(() => customers.filter((customer) => {
    const belongsToOffice = office.id === "all" || customer.office === office.name;
    const matchesStatus = status === "すべての契約状態" || customer.status === status;
    return belongsToOffice && matchesStatus && `${customer.name}${customer.kana}${customer.id}${customer.area}${customer.phone}`.toLowerCase().includes(query.toLowerCase());
  }), [query, office, customers, status]);

  return <div className="mx-auto max-w-7xl"><PageHeading title="顧客管理" description={`${office.name}・契約顧客 ${filtered.length.toLocaleString()}件（デモデータ）`} action={<button onClick={() => setFormOpen(true)} className="rounded-xl bg-[#2563EB] px-4 py-2.5 text-sm font-bold text-white shadow-sm">＋ 顧客を登録</button>} />
    <div className="rounded-2xl border border-[#E5E7EB] bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-[#E5E7EB] p-4 sm:flex-row"><div className="relative flex-1"><svg className="absolute left-3 top-3.5 h-5 w-5 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></svg><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="氏名・顧客番号・電話番号・住所で検索" className="h-12 w-full rounded-xl border border-[#E5E7EB] bg-[#F8FAFC] pl-11 pr-4 text-sm outline-none focus:border-[#2563EB] focus:ring-4 focus:ring-[#2563EB]/10" /></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-12 rounded-xl border border-[#E5E7EB] bg-white px-4 text-sm font-semibold text-slate-600"><option>すべての契約状態</option><option>契約中</option><option>一時休止</option><option>確認待ち</option></select><button className="h-12 rounded-xl border border-[#E5E7EB] px-4 text-sm font-bold">CSV出力</button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left"><thead className="bg-[#F8FAFC] text-xs font-bold text-slate-500"><tr><th className="px-5 py-4">顧客</th><th className="px-5 py-4">エリア</th><th className="px-5 py-4">契約商品</th><th className="px-5 py-4">配送</th><th className="px-5 py-4">担当営業</th><th className="px-5 py-4">状態</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{filtered.map((customer) => <tr key={customer.id} onClick={() => setSelected(customer)} className="cursor-pointer transition hover:bg-blue-50/40"><td className="px-5 py-4"><p className="text-sm font-bold">{customer.name}</p><p className="mt-1 text-xs text-slate-400">{customer.id}</p></td><td className="px-5 py-4 text-sm text-slate-600">{customer.area}</td><td className="px-5 py-4 text-sm text-slate-600">{customer.product}</td><td className="px-5 py-4 text-sm font-semibold">{customer.delivery}</td><td className="px-5 py-4 text-sm text-slate-600">{customer.sales}</td><td className="px-5 py-4"><StatusBadge tone={customer.status === "契約中" ? "green" : customer.status === "一時休止" ? "amber" : "blue"}>{customer.status}</StatusBadge></td></tr>)}</tbody></table></div>
      {filtered.length === 0 && <div className="py-16 text-center text-sm text-slate-500">条件に一致する顧客がいません</div>}
    </div>
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/30" onClick={() => setSelected(null)}><aside className="h-full w-full max-w-2xl overflow-y-auto bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-[#2563EB]">{selected.id}</p><h2 className="mt-2 text-2xl font-bold">{selected.name}</h2><p className="mt-1 text-sm text-slate-400">{selected.kana}</p></div><button onClick={() => setSelected(null)} className="rounded-lg bg-slate-100 p-2 text-slate-500">✕</button></div><div className="mt-5 flex gap-2 overflow-x-auto border-b pb-3">{["基本情報", "契約", "注文履歴", "配送履歴", "請求・入金", "メモ"].map((tab) => <button key={tab} onClick={() => setDetailTab(tab)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold ${detailTab === tab ? "bg-[#2563EB] text-white" : "bg-slate-100 text-slate-500"}`}>{tab}</button>)}</div>{detailTab === "基本情報" ? <div className="mt-6 grid gap-5 sm:grid-cols-2">{[["電話番号", selected.phone], ["住所", selected.area], ["契約商品", selected.product], ["配送曜日", selected.delivery], ["担当営業", selected.sales], ["営業所", selected.office]].map(([label, value]) => <div key={label} className="border-b border-[#E5E7EB] pb-4"><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-1.5 text-sm font-semibold">{value}</p></div>)}</div> : <div className="mt-6 space-y-3">{[1,2,3].map((item) => <div key={item} className="rounded-xl border border-[#E5E7EB] p-4"><div className="flex justify-between"><p className="text-sm font-bold">{detailTab} {item}</p><span className="text-xs text-slate-400">2026/08/{String(13-item).padStart(2,"0")}</span></div><p className="mt-2 text-sm text-slate-500">{detailTab}に関するデモ履歴を表示しています。</p></div>)}</div>}<div className="mt-7 grid grid-cols-2 gap-3"><button onClick={() => { setSelected(null); setFormOpen(true); }} className="rounded-xl border border-[#2563EB] py-3 text-sm font-bold text-[#2563EB]">顧客情報を編集</button><a href="/milmo/contract-performance" className="rounded-xl bg-[#2563EB] py-3 text-center text-sm font-bold text-white">契約・実績を開く</a></div></aside></div>}
    {formOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4" onClick={() => setFormOpen(false)}><form onSubmit={(event) => { event.preventDefault(); setCustomers((current) => [...current, { id: `C-${10490 + current.length}`, name: "新規 顧客", kana: "シンキ コキャク", office: "本社営業所", area: "江東区有明", product: "未契約", status: "確認待ち", delivery: "未設定", sales: "佐藤 美咲", phone: "090-0000-0000" }]); setFormOpen(false); }} className="max-h-[calc(100vh-2rem)] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b p-6"><h2 className="text-xl font-bold">顧客を登録</h2><button type="button" onClick={() => setFormOpen(false)}>✕</button></div><div className="grid gap-4 p-6 sm:grid-cols-2">{[["氏名","山田 花子"],["フリガナ","ヤマダ ハナコ"],["電話番号","090-1234-5678"],["メールアドレス","customer@example.jp"],["郵便番号","135-0063"],["住所","東京都江東区有明2-1-8"]].map(([label,value]) => <label key={label} className={`text-sm font-bold ${label === "住所" ? "sm:col-span-2" : ""}`}>{label}<input required defaultValue={value} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" /></label>)}<label className="text-sm font-bold">営業所<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 font-normal"><option>本社営業所</option><option>吉野ヶ里営業所</option></select></label><label className="text-sm font-bold">担当営業<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 font-normal"><option>佐藤 美咲</option><option>田中 悠斗</option></select></label></div><div className="flex justify-end gap-3 border-t bg-[#F8FAFC] p-4"><button type="button" onClick={() => setFormOpen(false)} className="rounded-xl border bg-white px-5 py-2.5 text-sm font-bold">キャンセル</button><button className="rounded-xl bg-[#2563EB] px-6 py-2.5 text-sm font-bold text-white">顧客を登録</button></div></form></div>}
  </div>;
}
