"use client";

import { useState } from "react";
import { PageHeading, StatusBadge } from "@/components/page-heading";
import { demoOrders } from "@/lib/demo";
import { useDemoOffice } from "@/lib/demo-office";

export default function OrdersPage() {
  const { office } = useDemoOffice();
  const [orders, setOrders] = useState(demoOrders);
  const [filter, setFilter] = useState("すべて");
  const [modalOpen, setModalOpen] = useState(false);
  const [selected, setSelected] = useState<(typeof demoOrders)[number] | null>(null);
  const shown = filter === "すべて" ? orders : orders.filter((order) => order.status === filter);
  function confirm(id: string) { setOrders((current) => current.map((order) => order.id === id ? { ...order, status: "確定" } : order)); }
  return <div className="mx-auto max-w-7xl"><PageHeading title="注文管理" description={`${office.name}・管理画面、電話、LINEからの注文を一元管理`} action={<button onClick={() => setModalOpen(true)} className="rounded-xl bg-[#2563EB] px-4 py-2.5 text-sm font-bold text-white">＋ 注文を登録</button>} />
    <div className="mb-4 flex gap-2 overflow-x-auto pb-1">{["すべて", "確認待ち", "確定", "準備中", "配送中"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${filter === item ? "bg-[#0F172A] text-white" : "border border-[#E5E7EB] bg-white text-slate-500"}`}>{item}</button>)}</div>
    <div className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[840px] text-left"><thead className="bg-[#F8FAFC] text-xs font-bold text-slate-500"><tr><th className="px-5 py-4">注文番号</th><th className="px-5 py-4">顧客</th><th className="px-5 py-4">注文経路</th><th className="px-5 py-4">商品</th><th className="px-5 py-4">金額</th><th className="px-5 py-4">状態</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{shown.map((order) => <tr key={order.id} className="hover:bg-blue-50/30"><td className="px-5 py-4"><p className="text-sm font-bold">{order.id}</p><p className="mt-1 text-xs text-slate-400">{order.date}</p></td><td className="px-5 py-4 text-sm font-semibold">{order.customer}</td><td className="px-5 py-4"><StatusBadge tone={order.channel === "LINE" ? "green" : order.channel === "電話" ? "amber" : "slate"}>{order.channel}</StatusBadge></td><td className="px-5 py-4 text-sm text-slate-600">{order.item}</td><td className="px-5 py-4 text-sm font-bold">¥{order.amount.toLocaleString()}</td><td className="px-5 py-4"><StatusBadge tone={order.status === "確認待ち" ? "red" : order.status === "確定" ? "blue" : "amber"}>{order.status}</StatusBadge></td><td className="px-5 py-4"><button onClick={() => setSelected(order)} className="text-xs font-bold text-[#2563EB]">詳細・処理 →</button></td></tr>)}</tbody></table></div></div>
    {(modalOpen || selected) && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4" onClick={() => { setModalOpen(false); setSelected(null); }}><div className="w-full max-w-xl rounded-2xl bg-white shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b p-6"><div><p className="text-xs font-bold text-[#2563EB]">{selected?.id ?? "新規注文"}</p><h2 className="mt-1 text-xl font-bold">{selected ? "注文詳細・処理" : "注文を登録"}</h2></div><button onClick={() => { setModalOpen(false); setSelected(null); }}>✕</button></div><div className="grid gap-4 p-6 sm:grid-cols-2"><label className="text-sm font-bold">顧客<input defaultValue={selected?.customer ?? "山田 花子"} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" /></label><label className="text-sm font-bold">注文経路<select defaultValue={selected?.channel ?? "電話"} className="mt-2 h-11 w-full rounded-xl border bg-white px-3 font-normal"><option>管理画面</option><option>電話</option><option>LINE</option></select></label><label className="text-sm font-bold sm:col-span-2">商品<input defaultValue={selected?.item ?? "有明牛乳 900ml × 2"} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" /></label><label className="text-sm font-bold">配送希望日<input type="date" defaultValue="2026-08-13" className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" /></label><label className="text-sm font-bold">金額<input type="number" defaultValue={selected?.amount ?? 560} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" /></label><label className="text-sm font-bold sm:col-span-2">注文メモ<textarea className="mt-2 h-20 w-full rounded-xl border p-3 font-normal" placeholder="配送場所や連絡事項" /></label></div><div className="flex flex-wrap justify-end gap-2 border-t bg-[#F8FAFC] p-4">{selected && <button onClick={() => { setOrders((current) => current.map((order) => order.id === selected.id ? { ...order, status: "キャンセル" } : order)); setSelected(null); }} className="mr-auto rounded-xl border border-red-200 bg-white px-4 py-2.5 text-sm font-bold text-red-600">注文をキャンセル</button>}<button onClick={() => { setModalOpen(false); setSelected(null); }} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">閉じる</button><button onClick={() => { if (selected) confirm(selected.id); else setOrders((current) => [{ id: `O-240812-${current.length + 19}`, customer: "山田 花子", channel: "管理画面", item: "有明牛乳 900ml × 2", amount: 560, status: "確定", date: "今日 11:40" }, ...current]); setModalOpen(false); setSelected(null); }} className="rounded-xl bg-[#2563EB] px-5 py-2.5 text-sm font-bold text-white">{selected ? "注文を確定" : "注文を登録"}</button></div></div></div>}
  </div>;
}
