"use client";

import { useState } from "react";
import { PageHeading } from "@/components/page-heading";
import { useDemoOffice } from "@/lib/demo-office";
import type { DemoScreen } from "@/lib/product-navigation";

const input = "mt-2 h-11 w-full rounded-xl border bg-white px-3 font-normal outline-none focus:border-violet-500";
const customers = [
  ["山田 花子", "東京都 / 関東", "健康維持", "#回答済み #高関心", "8/12 09:42"],
  ["鈴木 一郎", "佐賀県 / 九州", "商品を試したい", "#クーポン反応層", "8/11 18:20"],
  ["高橋 悦子", "福岡県 / 九州", "家族の健康", "#リピーター", "8/10 12:05"],
  ["伊藤 健二", "熊本県 / 九州", "健康維持", "#休眠候補", "5/09 20:18"],
];
const surveys = [
  ["山田 花子", "東京都", "健康維持", "ヨーグルト", "8/12 09:42"],
  ["鈴木 一郎", "佐賀県", "商品を試したい", "牛乳", "8/11 18:20"],
  ["高橋 悦子", "福岡県", "家族の健康", "宅配サービス", "8/10 12:05"],
];
const segments = [
  ["九州 × 健康維持 × 高関心", "386人", "自動更新", "8/13", "配信可能"],
  ["クーポン利用あり × 30日以内反応", "142人", "自動更新", "8/13", "配信可能"],
  ["90日間反応なし", "214人", "毎日更新", "8/13", "再来促進候補"],
];
const broadcasts = [
  ["夏の健康習慣キャンペーン", "8/15 10:00", "予約中", "九州 × 健康維持", "1,248人"],
  ["ヨーグルトクーポン", "8/10 09:00", "配信済み", "ヨーグルト関心層", "842人"],
  ["アンケート回答リマインド", "8/08 18:00", "配信済み", "開封済み・未回答", "126人"],
];
const tags = [
  ["#回答済み", "回答", "486人", "アンケート回答時", "自動"],
  ["#高関心", "行動", "142人", "配信クリック3回以上", "自動"],
  ["#休眠候補", "行動", "214人", "90日間反応なし", "自動"],
  ["#クーポン反応層", "行動", "98人", "クーポン利用あり", "自動"],
];

export function CommoOperationsScreen({ screen }: { screen: DemoScreen }) {
  if (screen.slug === "home") return <Home screen={screen} />;
  if (screen.slug === "segment-create") return <SegmentBuilder screen={screen} />;
  if (screen.slug === "broadcast-create") return <BroadcastBuilder screen={screen} />;
  if (screen.slug === "ai-message-create") return <MessageWriter screen={screen} />;
  if (screen.slug === "settings-auto-classification") return <Classification screen={screen} />;
  if (screen.slug === "settings-account") return <Account screen={screen} />;
  if (screen.slug === "ai-recommendations") return <Recommendations screen={screen} />;
  if (screen.slug === "settings-line") return <LineSettings screen={screen} />;
  if (["customer-analysis", "survey-analysis", "analysis-line", "analysis-customers", "analysis-broadcasts", "analysis-conversions"].includes(screen.slug)) return <Analysis screen={screen} />;
  return <DataList screen={screen} />;
}

function Frame({ screen, children, action }: { screen: DemoScreen; children: React.ReactNode; action?: React.ReactNode }) {
  const { office } = useDemoOffice();
  return <div className="mx-auto max-w-7xl"><div className="mb-3 text-xs font-bold text-slate-400">commo. / {screen.label}</div><PageHeading title={screen.label} description={`${office.name}・${screen.description}`} action={action} />{children}</div>;
}
function Kpis({ items }: { items: string[][] }) {
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map(([label,value,note]) => <div key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p><p className="mt-2 text-xs font-bold text-violet-600">{note}</p></div>)}</div>;
}

function Home({ screen }: { screen: DemoScreen }) {
  return <Frame screen={screen} action={<button className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white">この対象に配信する</button>}><Kpis items={[["LINE友だち","2,846人","今月 +38人"],["プロフィール充足率","72.4%","回答で +8.6pt"],["反応ユーザー","706人","直近30日"],["配信経由CV","62件","前月比 +14件"]]} /><div className="mt-5 grid gap-5 lg:grid-cols-[1.25fr_1fr]"><section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">顧客理解から成果まで</h2><p className="mt-1 text-xs text-slate-500">友だち追加後の顧客化と施策成果</p><div className="mt-6 grid gap-2 sm:grid-cols-5">{[["友だち","2,846"],["回答","486"],["分類済み","2,061"],["クリック","324"],["CV","62"]].map(([a,b],i) => <div key={a} className="relative rounded-xl bg-violet-50 p-4 text-center"><p className="text-xs font-bold text-violet-700">{a}</p><p className="mt-2 text-lg font-bold">{b}</p>{i < 4 && <span className="absolute -right-2 top-7 z-10 text-violet-300">→</span>}</div>)}</div><div className="mt-6 rounded-xl border border-violet-100 bg-violet-50/50 p-4"><p className="text-sm font-bold text-violet-900">今月の改善ポイント</p><p className="mt-2 text-sm leading-6 text-slate-600">開封済み・未回答の126人へ再案内すると、回答数が約31件増える見込みです。</p></div></section><section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">次に届ける候補</h2><div className="mt-4 space-y-3">{[["九州 × 健康維持 × 高関心","386人","商品理解コンテンツ"],["開封済み × 未回答","126人","回答リマインド"],["90日間反応なし","214人","再来クーポン"]].map(([name,count,next]) => <div key={name} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><p className="text-sm font-bold">{name}</p><span className="text-xs font-bold text-violet-600">{count}</span></div><p className="mt-2 text-xs text-slate-500">おすすめ：{next}</p></div>)}</div></section></div></Frame>;
}

function DataList({ screen }: { screen: DemoScreen }) {
  const [query,setQuery] = useState("");
  const c = screen.slug === "customers" ? { heads:["顧客","居住地域","主な関心・目的","属性・タグ","最終反応"], rows:customers, action:"セグメントを作成" } : screen.slug === "survey-responses" ? { heads:["回答者","都道府県","利用目的","興味カテゴリ","回答日時"], rows:surveys, action:"回答データを出力" } : screen.slug === "segments" ? { heads:["セグメント","対象人数","更新","最終集計","状態"], rows:segments, action:"新しいセグメント" } : screen.slug.startsWith("broadcast-") ? { heads:["配信","配信日時","状態","対象セグメント","対象人数"], rows:broadcasts, action:"新しい配信" } : { heads:["タグ","種別","対象人数","付与条件","付与方法"], rows:tags, action:"タグを作成" };
  const shown = c.rows.filter(row => row.join("").includes(query));
  return <Frame screen={screen} action={<button className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white">＋ {c.action}</button>}><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="名前・属性・タグ・状態で検索" className="h-11 flex-1 rounded-xl border bg-slate-50 px-4 text-sm outline-none focus:border-violet-500" /><button className="rounded-xl border px-4 text-sm font-bold">条件を追加</button></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{c.heads.map(h=><th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody className="divide-y">{shown.map(row=><tr key={row[0]} className="hover:bg-violet-50/30">{row.map((cell,i)=><td key={`${cell}-${i}`} className={`px-5 py-4 ${i===0?"font-bold":"text-slate-600"}`}>{cell}</td>)}</tr>)}</tbody></table></div></section>{screen.slug === "survey-responses" && <p className="mt-3 text-xs text-slate-500">回答の生データです。地域・顧客タイプ・タグなどの自動分類結果は顧客プロフィールで確認できます。</p>}</Frame>;
}

const analyses: Record<string,{title:string;metrics:string[][];groups:string[][]}> = {
  "customer-analysis":{title:"顧客像",metrics:[["プロフィール生成済み","2,061人","72.4%"],["高関心","142人","+18人"],["リピーター","618人","21.7%"],["休眠候補","214人","要フォロー"]],groups:[["九州","48%"],["関東","22%"],["健康維持","41%"],["家族の健康","28%"]]},
  "survey-analysis":{title:"回答から見える顧客ニーズ",metrics:[["回答数","486件","回答率 38.9%"],["新規属性","1,204件","自動生成"],["最多目的","健康維持","41%"],["最多関心","ヨーグルト","36%"]],groups:[["健康維持","41%"],["家族の健康","28%"],["商品を試したい","19%"],["その他","12%"]]},
  "analysis-line":{title:"友だちの状態",metrics:[["友だち","2,846人","+38人"],["有効友だち","2,607人","91.6%"],["ブロック","239人","8.4%"],["回答可能","2,607人","LIFF認証対象"]],groups:[["新規追加","38人"],["開封","68.4%"],["クリック","12.6%"],["ブロック","8.4%"]]},
  "analysis-customers":{title:"顧客属性・行動",metrics:[["アクティブ","1,924人","67.6%"],["最近利用","386人","30日以内"],["高関心","142人","クリック3回+"],["休眠候補","214人","90日無反応"]],groups:[["九州","48%"],["関東","22%"],["関西","16%"],["その他","14%"]]},
  "analysis-broadcasts":{title:"セグメント配信と通常配信の比較",metrics:[["配信数","12件","今月"],["開封率","68.4%","+4.8pt"],["クリック率","12.6%","+3.1pt"],["回答率","38.9%","+8.2pt"]],groups:[["セグメント開封","72%"],["通常配信開封","61%"],["セグメントCV","6.8%"],["通常配信CV","3.9%"]]},
  "analysis-conversions":{title:"配信からコンバージョンまで",metrics:[["CV数","62件","+14件"],["CV率","4.8%","+0.6pt"],["クーポン利用","38件","61.3%"],["売上貢献","¥286,400","+18.2%"]],groups:[["クリック済み","324人"],["商品ページ到達","186人"],["クーポン取得","98人"],["利用・購入","62人"]]},
};
function Analysis({screen}:{screen:DemoScreen}) { const c=analyses[screen.slug]; return <Frame screen={screen} action={<select className="rounded-xl border bg-white px-4 py-3 text-sm font-bold"><option>直近30日</option><option>直近90日</option></select>}><Kpis items={c.metrics}/><section className="mt-5 rounded-2xl border bg-white p-6"><h2 className="font-bold">{c.title}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{c.groups.map(([label,value],i)=><div key={label} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between"><span className="text-xs font-bold text-slate-600">{label}</span><span className="text-sm font-bold text-violet-700">{value}</span></div><div className="mt-3 h-2 rounded-full bg-violet-100"><div className="h-full rounded-full bg-violet-500" style={{width:`${[76,62,48,34][i]}%`}}/></div></div>)}</div></section></Frame>; }

function SegmentBuilder({screen}:{screen:DemoScreen}) { const [saved,setSaved]=useState(false); return <Frame screen={screen}><div className="grid gap-5 lg:grid-cols-[1fr_340px]"><section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">顧客条件を掛け合わせる</h2><div className="mt-5 space-y-3">{[["地域","が次と一致","九州"],["利用目的","が次と一致","健康維持"],["配信クリック数","以上","3"]].map((row,i)=><div key={row[0]} className="grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-[54px_1fr_1fr_1fr]"><span className="self-center text-xs font-bold text-violet-600">{i?"AND":"条件"}</span>{row.map(v=><input key={v} defaultValue={v} className="h-11 rounded-lg border bg-white px-3 text-sm"/>)}</div>)}</div><button className="mt-3 text-sm font-bold text-violet-600">＋ 条件を追加</button><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>setSaved(true)} className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white">セグメントとして保存</button><button className="rounded-xl border px-5 py-3 text-sm font-bold">対象ユーザーを見る</button></div>{saved&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700">保存しました（デモ）</p>}</section><aside className="rounded-2xl border border-violet-100 bg-violet-50/60 p-5"><p className="text-sm font-bold text-violet-800">該当する顧客</p><p className="mt-3 text-3xl font-bold">142人</p><p className="mt-2 text-xs text-slate-500">有効友だち 138人 / 配信可能 138人</p><button className="mt-6 w-full rounded-xl bg-violet-600 py-3 text-sm font-bold text-white">この対象に配信する</button></aside></div></Frame>; }

function BroadcastBuilder({screen}:{screen:DemoScreen}) { const [saved,setSaved]=useState(false); return <Frame screen={screen}><form onSubmit={e=>{e.preventDefault();setSaved(true)}} className="grid gap-5 lg:grid-cols-[1fr_340px]"><section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">配信内容</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">配信対象セグメント<select className={input}><option>九州 × 健康維持 × 高関心</option><option>開封済み × 未回答</option></select></label><label className="text-sm font-bold">対象人数<input readOnly value="386人" className={`${input} bg-slate-50`}/></label><label className="text-sm font-bold sm:col-span-2">タイトル<input className={input} placeholder="配信タイトル"/></label><label className="text-sm font-bold sm:col-span-2">本文<textarea className="mt-2 h-36 w-full rounded-xl border p-3 font-normal" placeholder="LINEで届ける内容を入力"/></label><label className="text-sm font-bold sm:col-span-2">CTA URL<input className={input} placeholder="LIFFアンケートURL / 商品ページURL"/></label><label className="text-sm font-bold">配信日時<input type="datetime-local" defaultValue="2026-08-15T10:00" className={input}/></label></div><div className="mt-6 flex flex-wrap gap-3"><button type="button" className="rounded-xl border px-5 py-3 text-sm font-bold">テスト送信</button><button className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white">配信予約</button><button type="button" className="rounded-xl border border-violet-300 px-5 py-3 text-sm font-bold text-violet-700">即時配信</button></div>{saved&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700">配信を予約しました（デモ）</p>}</section><aside className="rounded-2xl border border-violet-100 bg-violet-50/60 p-5"><h2 className="font-bold text-violet-800">配信後に計測</h2><div className="mt-4 space-y-2 text-sm text-slate-600">{["配信・開封・クリック","アンケート回答","クーポン利用・購入","ブロック","クリック済み未CV"].map(x=><p key={x} className="rounded-lg bg-white px-3 py-2">✓ {x}</p>)}</div></aside></form></Frame>; }

function MessageWriter({screen}:{screen:DemoScreen}) {
  const [tone,setTone]=useState("やさしい");
  return <Frame screen={screen}><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(420px,0.9fr)]"><section className="rounded-2xl border bg-white p-6 shadow-sm"><div><h2 className="font-bold">施策と顧客像を指定</h2><p className="mt-1 text-xs text-slate-500">誰に、何をしてほしいかをもとに文章を作成します。</p></div><label className="mt-5 block text-sm font-bold">目的<select className={input}><option>アンケート回答促進</option><option>クーポン利用促進</option></select></label><label className="mt-4 block text-sm font-bold">対象セグメント<select className={input}><option>開封済み × 未回答（126人）</option></select></label><div className="mt-4"><p className="text-sm font-bold">文章の雰囲気</p><div className="mt-2 flex flex-wrap gap-2">{["やさしい","簡潔","親しみやすい"].map(item=><button type="button" key={item} onClick={()=>setTone(item)} className={`rounded-full border px-4 py-2 text-xs font-bold ${tone===item?"border-violet-600 bg-violet-50 text-violet-700":"text-slate-500"}`}>{item}</button>)}</div></div><label className="mt-4 block text-sm font-bold">伝えたい内容<textarea className="mt-2 h-28 w-full rounded-xl border p-3 font-normal outline-none focus:border-violet-500" defaultValue="回答は1分。回答後に使えるクーポンを案内する。"/></label><button className="mt-5 w-full rounded-xl bg-violet-600 py-3 text-sm font-bold text-white shadow-sm">文章を作成する</button></section><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-6 py-4"><div><h2 className="font-bold">生成案</h2><p className="mt-1 text-xs text-slate-500">LINEでの表示イメージ</p></div><button className="rounded-lg border px-3 py-2 text-xs font-bold text-slate-600">再生成</button></div><div className="bg-slate-100 p-5 sm:p-7"><div className="mx-auto max-w-md overflow-hidden rounded-[24px] border border-slate-200 bg-[#f4f5f7] shadow-sm"><div className="border-b bg-white px-4 py-3 text-center"><p className="text-xs font-bold">有明乳業 公式LINE</p></div><div className="flex gap-3 p-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-violet-600 text-xs font-bold text-white">有</div><div className="min-w-0 max-w-[82%]"><p className="mb-1 text-[10px] text-slate-500">有明乳業</p><div className="rounded-2xl rounded-tl-sm bg-white p-4 text-sm leading-7 shadow-sm"><p>こんにちは、有明乳業です。</p><p className="mt-3">よりあなたに合った情報をお届けするため、1分で終わるアンケートにご協力ください。</p><p className="mt-3">回答後に使えるクーポンをご用意しています。</p><a className="mt-4 block rounded-xl bg-violet-600 px-4 py-3 text-center text-xs font-bold text-white">アンケートに回答する</a></div><p className="mt-1 text-right text-[10px] text-slate-400">10:00</p></div></div></div></div><div className="border-t px-6 py-4"><div className="flex items-center justify-between text-xs text-slate-500"><span>本文 67文字</span><button className="font-bold text-violet-700">文章をコピー</button></div><button className="mt-4 w-full rounded-xl bg-violet-600 py-3 text-sm font-bold text-white">この文章で配信を作る</button></div></section></div></Frame>;
}

function Classification({screen}:{screen:DemoScreen}) { return <Frame screen={screen} action={<button className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white">ルールを追加</button>}><div className="space-y-4">{[["都道府県 → 地域","福岡県・佐賀県・長崎県・熊本県・大分県・宮崎県・鹿児島県・沖縄県","地域 = 九州 / #九州"],["高関心","配信クリック数が3回以上","#高関心"],["休眠候補","最終反応から90日以上","#休眠候補"],["アンケート回答済み","回答を1件保存","#回答済み"]].map(([name,condition,result])=><section key={name} className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-[220px_1fr_240px]"><div><p className="text-xs font-bold text-violet-600">自動分類</p><p className="mt-1 font-bold">{name}</p></div><div><p className="text-xs text-slate-400">条件</p><p className="mt-1 text-sm">{condition}</p></div><div><p className="text-xs text-slate-400">生成する属性・タグ</p><p className="mt-1 text-sm font-bold">{result}</p></div></section>)}</div></Frame>; }

function Recommendations({screen}:{screen:DemoScreen}) { return <Frame screen={screen}><div className="grid gap-4 lg:grid-cols-2">{[["回答リマインド","開封済み・未回答の126人へ、回答特典を明確にした再案内がおすすめです。","回答 +31件見込み"],["高関心層へ商品提案","九州在住で健康維持に関心が高い142人へ、ヨーグルトの利用シーンを届けます。","CV率 +2.4pt見込み"],["休眠顧客の掘り起こし","90日間反応がない214人へ、選べるクーポンを案内します。","反応 +28件見込み"],["新規友だちの理解促進","直近30日の新規友だち186人へ、プロフィールアンケートを届けます。","分類率 +12pt見込み"]].map(([title,desc,effect])=><article key={title} className="rounded-2xl border bg-white p-6"><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">AIおすすめ</span><h2 className="mt-4 text-lg font-bold">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{desc}</p><div className="mt-5 flex items-center justify-between gap-3"><span className="text-xs font-bold text-emerald-600">{effect}</span><button className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white">施策を作成</button></div></article>)}</div></Frame>; }

function LineSettings({screen}:{screen:DemoScreen}) { return <Frame screen={screen}><div className="grid gap-5 lg:grid-cols-[1fr_340px]"><section className="rounded-2xl border bg-white p-6"><div className="flex justify-between"><div><p className="text-sm font-bold">LINE公式アカウント</p><p className="mt-1 text-xs text-slate-500">有明乳業 公式LINE</p></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">● 連携中</span></div><dl className="mt-6 divide-y">{[["LIFF","設定済み・認証必須"],["Messaging API","Webhook 正常"],["友だち状態同期","正常"],["最終同期","2026/08/13 00:20"]].map(([l,v])=><div key={l} className="flex justify-between py-4 text-sm"><dt className="text-slate-500">{l}</dt><dd className="font-bold">{v}</dd></div>)}</dl></section><aside className="rounded-2xl border bg-white p-6"><h2 className="font-bold">回答アクセス制御</h2><div className="mt-4 space-y-3 text-sm">{["LIFF内ユーザーのみ","登録済みLINEユーザーのみ","友だち状態のみ","1ユーザー1回答"].map(x=><p key={x} className="flex justify-between"><span>{x}</span><b className="text-emerald-600">有効</b></p>)}</div></aside></div></Frame>; }

function Account({screen}:{screen:DemoScreen}) { return <Frame screen={screen}><section className="max-w-3xl rounded-2xl border bg-white p-6"><h2 className="font-bold">アカウント情報</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["クライアント名","有明乳業株式会社"],["サービス名","有明乳業 宅配サービス"],["管理画面名","commo. 顧客マーケティング"],["主要CV","クーポン利用・商品購入・申込み"]].map(([label,value])=><label key={label} className="text-sm font-bold">{label}<input className={input} defaultValue={value}/></label>)}</div><button className="mt-6 rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white">保存する</button></section></Frame>; }
