"use client";

import { useMemo, useState } from "react";
import { PageHeading, StatusBadge } from "@/components/page-heading";
import { useDemoOffice } from "@/lib/demo-office";
import type { DemoScreen } from "@/lib/product-navigation";
import type { LegacyConfig } from "@/lib/milmo-legacy-screens";

const customers = ["山田 花子", "鈴木 一郎", "高橋 悦子", "伊藤 健二", "渡辺 直子"];
const products = ["有明牛乳 900ml", "のむヨーグルト", "低脂肪乳 900ml", "宅配専用コーヒー", "乳酸菌飲料セット"];

function downloadDemoCsv(label: string) {
  const csv = `項目,顧客,商品,数量,金額\n${label},山田 花子,有明牛乳 900ml,2,560\n${label},鈴木 一郎,のむヨーグルト,4,640\n`;
  const url = URL.createObjectURL(new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${label}.csv`; anchor.click(); URL.revokeObjectURL(url);
}

export function MilmoLegacySuiteScreen({ screen, config }: { screen: DemoScreen; config: LegacyConfig }) {
  if (config.mode === "report") return <LegacyReport screen={screen} config={config} />;
  if (config.mode === "master") return <LegacyMaster screen={screen} config={config} />;
  if (config.mode === "workflow") return <LegacyWorkflow screen={screen} config={config} />;
  if (config.mode === "batch") return <LegacyBatch screen={screen} config={config} />;
  return <LegacyUtility screen={screen} config={config} />;
}

function Frame({ screen, config, children, actions }: { screen: DemoScreen; config: LegacyConfig; children: React.ReactNode; actions?: React.ReactNode }) {
  const { office } = useDemoOffice();
  return <div className="mx-auto max-w-7xl"><div className="mb-3 flex items-center gap-2 text-xs font-bold text-slate-400"><span>milmo.</span><span>/</span><span>{config.category}</span><span>/</span><span>{screen.label}</span></div><PageHeading title={screen.label} description={`${office.name}・${screen.description}`} action={actions} />{children}</div>;
}

function FilterPanel({ extended = false }: { extended?: boolean }) {
  return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold text-slate-500">対象期間<div className="mt-2 flex gap-2"><input type="date" defaultValue="2026-08-01" className="h-11 min-w-0 flex-1 rounded-xl border px-3 text-sm font-normal" /><input type="date" defaultValue="2026-08-31" className="h-11 min-w-0 flex-1 rounded-xl border px-3 text-sm font-normal" /></div></label><label className="text-xs font-bold text-slate-500">営業所<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal"><option>全営業所</option><option>本社営業所</option><option>吉野ヶ里営業所</option></select></label><label className="text-xs font-bold text-slate-500">コース・順路<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal"><option>すべて</option><option>有明 Aコース 1〜50</option><option>有明 Bコース 1〜40</option></select></label><label className="text-xs font-bold text-slate-500">商品範囲<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal"><option>全商品</option>{products.slice(0,3).map((p) => <option key={p}>{p}</option>)}</select></label>{extended && <><label className="text-xs font-bold text-slate-500">集金区分<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal"><option>すべて</option><option>訪問集金</option><option>口座振替</option><option>振込</option></select></label><label className="text-xs font-bold text-slate-500">担当者<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal"><option>すべて</option><option>佐藤 美咲</option><option>田中 悠斗</option></select></label><label className="text-xs font-bold text-slate-500">出力順<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal"><option>配送コース・順路順</option><option>顧客番号順</option><option>商品順</option><option>金額順</option></select></label><label className="text-xs font-bold text-slate-500">対象状態<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal"><option>すべて</option><option>契約中</option><option>休止中</option><option>解約</option></select></label></>}</div>;
}

function LegacyReport({ screen, config }: { screen: DemoScreen; config: LegacyConfig }) {
  const [preview, setPreview] = useState(true);
  const [view, setView] = useState("表形式");
  const rows = useMemo(() => customers.map((customer, index) => ({ no: index + 1, customer, course: `A-${String(index + 1).padStart(2,"0")}`, product: products[index], count: index + 1, amount: 560 + index * 420 })), []);
  return <Frame screen={screen} config={config} actions={<div className="flex gap-2"><button onClick={() => downloadDemoCsv(screen.label)} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">CSV</button><button onClick={() => window.print()} className="rounded-xl bg-[#2563EB] px-4 py-2.5 text-sm font-bold text-white">印刷・PDF</button></div>}><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 flex flex-wrap gap-2">{["表形式", "集計表", "グラフ"].map((item) => <button key={item} onClick={() => setView(item)} className={`rounded-full px-4 py-2 text-xs font-bold ${view === item ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-500"}`}>{item}</button>)}</div><FilterPanel extended /><div className="mt-5 flex flex-wrap gap-4 text-sm text-slate-600"><label><input type="checkbox" defaultChecked className="mr-2" />得意先情報</label><label><input type="checkbox" defaultChecked className="mr-2" />数量ゼロを除く</label><label><input type="checkbox" className="mr-2" />解約者を含む</label><label><input type="checkbox" defaultChecked className="mr-2" />税別表示</label><label><input type="checkbox" className="mr-2" />改ページ</label></div><div className="mt-5 flex justify-end"><button onClick={() => setPreview(true)} className="rounded-xl border border-[#2563EB] px-6 py-2.5 text-sm font-bold text-[#2563EB]">表示・集計</button></div></section>{preview && <section className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">{screen.label} プレビュー</h2><p className="mt-1 text-xs text-slate-400">2026年8月・全コース</p></div><StatusBadge tone="blue">{view}</StatusBadge></div>{view === "グラフ" ? <div className="flex h-72 items-end gap-6 p-8">{rows.map((row) => <div key={row.no} className="flex h-full flex-1 flex-col justify-end"><div className="rounded-t-lg bg-[#2563EB]" style={{ height: `${35 + row.no * 11}%` }} /><p className="mt-2 truncate text-center text-xs">{row.customer.split(" ")[0]}</p></div>)}</div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#F8FAFC] text-xs text-slate-500"><tr>{["No.","コース", "顧客", "商品・内容", "数量", "金額"].map((h) => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={row.no}><td className="px-5 py-3">{row.no}</td><td className="px-5 py-3">{row.course}</td><td className="px-5 py-3 font-bold">{row.customer}</td><td className="px-5 py-3">{row.product}</td><td className="px-5 py-3">{row.count}</td><td className="px-5 py-3 font-bold">¥{row.amount.toLocaleString()}</td></tr>)}</tbody><tfoot className="border-t-2 bg-[#F8FAFC] font-bold"><tr><td colSpan={4} className="px-5 py-3 text-right">合計</td><td className="px-5 py-3">15</td><td className="px-5 py-3">¥7,000</td></tr></tfoot></table></div>}</section>}</Frame>;
}

function LegacyBatch({ screen, config }: { screen: DemoScreen; config: LegacyConfig }) {
  const [selected, setSelected] = useState<number[]>([0, 2]);
  const [done, setDone] = useState(false);
  const [mode, setMode] = useState("対象を抽出");
  const rows = customers.map((customer, index) => ({ id: `C-${10482-index*3}`, customer, before: index % 2 ? "のむヨーグルト / ¥160" : "有明牛乳 / ¥280", after: index % 2 ? "乳酸菌飲料 / ¥180" : "有明牛乳 / ¥300", status: index === 3 ? "要確認" : "変更可能" }));
  return <Frame screen={screen} config={config} actions={<button onClick={() => setDone(true)} className="rounded-xl bg-[#2563EB] px-5 py-2.5 text-sm font-bold text-white">選択した{selected.length}件を実行</button>}><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 flex gap-2">{["対象を抽出", "変更内容を確認", "処理履歴"].map((item) => <button key={item} onClick={() => setMode(item)} className={`rounded-full px-4 py-2 text-xs font-bold ${mode === item ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-500"}`}>{item}</button>)}</div><FilterPanel /><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-xs font-bold text-slate-500">変更前・処理元<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal"><option>有明牛乳 900ml</option><option>旧単価 ¥280</option><option>有明 Aコース</option></select></label><label className="text-xs font-bold text-slate-500">変更後・処理先<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal"><option>低脂肪乳 900ml</option><option>新単価 ¥300</option><option>有明 Bコース</option></select></label><label className="text-xs font-bold text-slate-500">適用日<input type="date" defaultValue="2026-09-01" className="mt-2 h-11 w-full rounded-xl border px-3 text-sm font-normal" /></label></div></section><section className="mt-5 overflow-hidden rounded-2xl border bg-white"><div className="flex justify-between border-b p-4"><p className="text-sm font-bold">対象一覧</p><div className="flex gap-3"><button onClick={() => setSelected(rows.map((_, i) => i))} className="text-xs font-bold text-[#2563EB]">全選択</button><button onClick={() => setSelected([])} className="text-xs font-bold text-slate-400">解除</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#F8FAFC] text-xs text-slate-500"><tr><th className="p-4">対象</th><th className="p-4">顧客</th><th className="p-4">変更前</th><th className="p-4">変更後</th><th className="p-4">状態</th></tr></thead><tbody className="divide-y">{rows.map((row, index) => <tr key={row.id}><td className="p-4"><input type="checkbox" checked={selected.includes(index)} onChange={() => setSelected((current) => current.includes(index) ? current.filter((i) => i !== index) : [...current, index])} /></td><td className="p-4"><p className="font-bold">{row.customer}</p><p className="text-xs text-slate-400">{row.id}</p></td><td className="p-4 text-slate-500">{row.before}</td><td className="p-4 font-bold text-[#2563EB]">{row.after}</td><td className="p-4"><StatusBadge tone={row.status === "要確認" ? "amber" : "green"}>{row.status}</StatusBadge></td></tr>)}</tbody></table></div></section>{done && <button onClick={() => setDone(false)} className="fixed bottom-6 right-6 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white shadow-xl">✓ {selected.length}件を処理しました（デモ）</button>}</Frame>;
}

function LegacyMaster({ screen, config }: { screen: DemoScreen; config: LegacyConfig }) {
  const initial = Array.from({ length: 5 }, (_, index) => ({ code: `${screen.slug.slice(-3).toUpperCase()}-${String(index + 1).padStart(3,"0")}`, name: index < customers.length ? customers[index] : `${screen.label} ${index+1}`, category: config.category, detail: index % 2 ? "標準設定" : "本社共通", active: index !== 4 }));
  const [rows, setRows] = useState(initial);
  const [query, setQuery] = useState("");
  const [editing, setEditing] = useState<(typeof initial)[number] | null>(null);
  const shown = rows.filter((row) => `${row.code}${row.name}${row.detail}`.includes(query));
  return <Frame screen={screen} config={config} actions={<button onClick={() => setEditing({ code: "新規", name: "", category: config.category, detail: "", active: true })} className="rounded-xl bg-[#2563EB] px-5 py-2.5 text-sm font-bold text-white">＋ 新規登録</button>}><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex gap-3 border-b p-4"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={`${screen.label}をコード・名称で検索`} className="h-11 flex-1 rounded-xl border bg-[#F8FAFC] px-4 text-sm" /><button onClick={() => downloadDemoCsv(screen.label)} className="rounded-xl border px-4 text-sm font-bold">CSV</button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#F8FAFC] text-xs text-slate-500"><tr><th className="p-4">コード</th><th className="p-4">名称</th><th className="p-4">区分</th><th className="p-4">設定内容</th><th className="p-4">状態</th><th /></tr></thead><tbody className="divide-y">{shown.map((row) => <tr key={row.code}><td className="p-4 font-bold text-[#2563EB]">{row.code}</td><td className="p-4 font-bold">{row.name}</td><td className="p-4 text-slate-500">{row.category}</td><td className="p-4 text-slate-500">{row.detail}</td><td className="p-4"><StatusBadge tone={row.active ? "green" : "slate"}>{row.active ? "使用中" : "停止"}</StatusBadge></td><td className="p-4"><button onClick={() => setEditing(row)} className="text-xs font-bold text-[#2563EB]">編集 →</button></td></tr>)}</tbody></table></div></section>{editing && <Modal title={`${screen.label}を${editing.code === "新規" ? "登録" : "編集"}`} onClose={() => setEditing(null)} onSave={() => { if (editing.code === "新規") setRows((current) => [...current, { ...editing, code: `NEW-${current.length+1}`, name: editing.name || `新しい${screen.label}` }]); else setRows((current) => current.map((row) => row.code === editing.code ? editing : row)); setEditing(null); }}><div className="grid gap-4 sm:grid-cols-2"><Input label="コード" value={editing.code} /><Input label="名称" value={editing.name} onChange={(name) => setEditing({ ...editing, name })} /><Input label="分類・区分" value={editing.category} /><Input label="設定内容" value={editing.detail} onChange={(detail) => setEditing({ ...editing, detail })} /><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={editing.active} onChange={(e) => setEditing({ ...editing, active: e.target.checked })} />使用する</label></div></Modal>}</Frame>;
}

function LegacyWorkflow({ screen, config }: { screen: DemoScreen; config: LegacyConfig }) {
  const steps = ["対象データ確認", "エラーチェック", "データ作成・取込", "結果確認", "反映完了"];
  const [step, setStep] = useState(1);
  const [fileName, setFileName] = useState("MILMO_20260812.dat");
  return <Frame screen={screen} config={config} actions={<button onClick={() => setStep(steps.length)} className="rounded-xl bg-[#2563EB] px-5 py-2.5 text-sm font-bold text-white">一括実行</button>}><div className="grid gap-5 lg:grid-cols-[1fr_340px]"><div className="space-y-5"><section className="rounded-2xl border bg-white p-5"><FilterPanel /><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#F8FAFC] p-4"><p className="text-xs text-slate-400">対象件数</p><p className="mt-2 text-xl font-bold">1,284件</p></div><div className="rounded-xl bg-[#F8FAFC] p-4"><p className="text-xs text-slate-400">対象金額</p><p className="mt-2 text-xl font-bold">¥5,082,400</p></div><div className="rounded-xl bg-red-50 p-4"><p className="text-xs text-red-400">エラー</p><p className="mt-2 text-xl font-bold text-red-600">3件</p></div></div></section><section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3"><input value={fileName} onChange={(e) => setFileName(e.target.value)} className="h-11 flex-1 rounded-xl border px-3 text-sm" /><button className="rounded-xl border px-4 py-2.5 text-sm font-bold">ファイル選択</button><button className="rounded-xl border px-4 py-2.5 text-sm font-bold">内容確認</button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead className="bg-[#F8FAFC]"><tr><th className="p-3">データ</th><th className="p-3">件数</th><th className="p-3">金額</th><th className="p-3">結果</th></tr></thead><tbody><tr><td className="p-3">{fileName}</td><td className="p-3">1,284</td><td className="p-3">¥5,082,400</td><td className="p-3"><StatusBadge tone="green">確認済み</StatusBadge></td></tr></tbody></table></div></section></div><aside className="rounded-2xl border bg-white p-5">{steps.map((label, index) => <div key={label} className="mb-3 flex gap-3 rounded-xl border p-3"><span className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${index < step ? "bg-emerald-100 text-emerald-700" : index === step ? "bg-blue-100 text-blue-700" : "bg-slate-100 text-slate-400"}`}>{index < step ? "✓" : index+1}</span><div><p className="text-sm font-bold">{label}</p><p className="text-xs text-slate-400">{index < step ? "完了" : index === step ? "実行可能" : "待機中"}</p></div></div>)}<button disabled={step >= steps.length} onClick={() => setStep((current) => current+1)} className="mt-3 w-full rounded-xl bg-[#2563EB] py-3 text-sm font-bold text-white disabled:bg-emerald-500">{step >= steps.length ? "✓ 処理完了" : `${steps[step]}へ進む`}</button></aside></div></Frame>;
}

function LegacyUtility({ screen, config }: { screen: DemoScreen; config: LegacyConfig }) {
  const [saved, setSaved] = useState(false);
  const isMap = screen.slug.includes("coordinate") || screen.slug.includes("navigation");
  return <Frame screen={screen} config={config} actions={<button onClick={() => setSaved(true)} className="rounded-xl bg-[#2563EB] px-5 py-2.5 text-sm font-bold text-white">設定を保存</button>}><div className={`grid gap-5 ${isMap ? "lg:grid-cols-[380px_1fr]" : "lg:grid-cols-[1fr_340px]"}`}><section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">{screen.label}の設定</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="対象名称" value={screen.label} /><Input label="適用開始日" value="2026-09-01" type="date" /><label className="text-sm font-bold">処理区分<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 font-normal"><option>標準</option><option>営業所別</option><option>コース別</option></select></label><label className="text-sm font-bold">出力・適用方法<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 font-normal"><option>確認後に適用</option><option>一括適用</option></select></label><label className="text-sm font-bold sm:col-span-2">備考<textarea className="mt-2 h-24 w-full rounded-xl border p-3 font-normal" placeholder="設定内容・注意事項" /></label></div>{isMap && <div className="mt-5"><Input label="住所・座標検索" value="東京都江東区有明2-1-8" /><div className="mt-3 flex gap-2"><button className="rounded-xl border px-4 py-2 text-sm font-bold">住所から座標取得</button><button onClick={() => downloadDemoCsv(screen.label)} className="rounded-xl border px-4 py-2 text-sm font-bold">CSV出力</button></div></div>}</section>{isMap ? <div className="relative min-h-96 overflow-hidden rounded-2xl border bg-[#dfead8] shadow-sm"><div className="absolute inset-0 opacity-40" style={{ backgroundImage: "linear-gradient(30deg,#fff 12%,transparent 12.5%,transparent 87%,#fff 87.5%),linear-gradient(150deg,#fff 12%,transparent 12.5%,transparent 87%,#fff 87.5%)", backgroundSize: "80px 140px" }} /><div className="absolute left-[45%] top-[42%] flex h-12 w-12 items-center justify-center rounded-full bg-[#2563EB] font-bold text-white shadow-xl">1</div><div className="absolute bottom-4 left-4 rounded-xl bg-white p-4 shadow"><p className="text-xs font-bold text-[#2563EB]">C-10482 山田 花子</p><p className="mt-1 text-xs text-slate-500">緯度 35.6308 / 経度 139.7931</p></div></div> : <aside className="rounded-2xl border border-blue-100 bg-blue-50 p-5"><h2 className="font-bold text-blue-800">設定内容</h2><p className="mt-3 text-sm leading-6 text-blue-700">現在の設定を変更し、保存ボタンでデモ反映できます。</p>{saved && <p className="mt-5 rounded-xl bg-white p-3 text-sm font-bold text-emerald-700">✓ 設定を保存しました</p>}</aside>}</div>{saved && isMap && <button onClick={() => setSaved(false)} className="fixed bottom-6 right-6 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">✓ 設定を保存しました（デモ）</button>}</Frame>;
}

function Modal({ title, children, onClose, onSave }: { title: string; children: React.ReactNode; onClose: () => void; onSave: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4" onMouseDown={onClose}><div className="w-full max-w-xl rounded-2xl bg-white shadow-2xl" onMouseDown={(e) => e.stopPropagation()}><div className="flex justify-between border-b p-5"><h2 className="text-xl font-bold">{title}</h2><button onClick={onClose}>✕</button></div><div className="p-6">{children}</div><div className="flex justify-end gap-3 border-t bg-[#F8FAFC] p-4"><button onClick={onClose} className="rounded-xl border bg-white px-5 py-2.5 text-sm font-bold">キャンセル</button><button onClick={onSave} className="rounded-xl bg-[#2563EB] px-6 py-2.5 text-sm font-bold text-white">保存する</button></div></div></div>; }
function Input({ label, value, type = "text", onChange }: { label: string; value: string; type?: string; onChange?: (value: string) => void }) { return <label className="text-sm font-bold">{label}<input type={type} value={value} onChange={(e) => onChange?.(e.target.value)} readOnly={!onChange} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" /></label>; }
