"use client";

import { useMemo, useState } from "react";
import { PageHeading, StatusBadge } from "@/components/page-heading";
import { useDemoOffice } from "@/lib/demo-office";
import type { DemoProduct, DemoScreen } from "@/lib/product-navigation";
import { ProductLogo } from "@/components/product-logo";

const sampleNames = ["山田 花子", "鈴木 一郎", "高橋 悦子", "伊藤 健二", "渡辺 直子"];
const sampleProducts = ["有明牛乳 900ml", "のむヨーグルト", "低脂肪乳 900ml", "宅配専用コーヒー", "乳酸菌飲料セット"];

export function ProductDemoScreen({ product, screen }: { product: DemoProduct; screen: DemoScreen }) {
  const { office } = useDemoOffice();
  const [query, setQuery] = useState("");
  const [selectedRow, setSelectedRow] = useState<number | null>(null);
  const [message, setMessage] = useState("");
  const [preview, setPreview] = useState(false);
  const [processDone, setProcessDone] = useState(false);

  const rows = useMemo(() => sampleNames.map((name, index) => ({
    id: `${product.id.toUpperCase()}-${String(index + 241).padStart(4, "0")}`,
    name,
    product: sampleProducts[index],
    date: `2026/08/${String(index + 1).padStart(2, "0")}`,
    amount: 1280 + index * 460,
    status: index === 0 ? "確認待ち" : index === 1 ? "処理中" : "完了",
  })).filter((row) => `${row.id}${row.name}${row.product}`.toLowerCase().includes(query.toLowerCase())), [product.id, query]);

  return <div className="mx-auto max-w-7xl">
    <div className="mb-3 flex items-center gap-2 text-xs font-bold text-slate-400"><ProductLogo product={product} size={20} /><span className={`font-logo ${product.id === "milmo" ? "text-base font-bold text-[#2563EB]" : "text-[10px] font-normal text-[#0F172A]"}`}>{product.name}<span className={product.dotColor}>.</span></span><span>/</span><span>{screen.label}</span></div>
    <PageHeading title={screen.label} description={`${office.name}・${screen.description}`} action={<span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">操作デモ</span>} />
    {screen.kind === "list" && <ListDemo rows={rows} query={query} setQuery={setQuery} onSelect={setSelectedRow} label={screen.label} />}
    {screen.kind === "form" && <FormDemo screen={screen} message={message} setMessage={setMessage} />}
    {screen.kind === "report" && <ReportDemo screen={screen} preview={preview} setPreview={setPreview} rows={rows} />}
    {screen.kind === "analysis" && <AnalysisDemo screen={screen} />}
    {screen.kind === "status" && <StatusDemo screen={screen} done={processDone} setDone={setProcessDone} />}
    {selectedRow !== null && <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/30" onClick={() => setSelectedRow(null)}><aside className="h-full w-full max-w-md bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[#2563EB]">{rows[selectedRow]?.id}</p><h2 className="mt-2 text-xl font-bold">{screen.label}の詳細</h2></div><button onClick={() => setSelectedRow(null)} className="rounded-lg bg-slate-100 p-2">✕</button></div><div className="mt-6 space-y-4">{[["対象", rows[selectedRow]?.name], ["商品・内容", rows[selectedRow]?.product], ["処理日", rows[selectedRow]?.date], ["金額", `¥${rows[selectedRow]?.amount.toLocaleString()}`], ["状態", rows[selectedRow]?.status]].map(([label, value]) => <div key={label} className="border-b border-[#E5E7EB] pb-4"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1.5 text-sm font-semibold">{value}</p></div>)}</div><button onClick={() => { setSelectedRow(null); setMessage("デモ更新しました"); }} className="mt-7 w-full rounded-xl bg-[#2563EB] py-3 text-sm font-bold text-white">編集する</button></aside></div>}
    {message && screen.kind !== "form" && <div className="fixed bottom-6 right-6 rounded-xl bg-[#0F172A] px-5 py-3 text-sm font-bold text-white shadow-xl">{message}</div>}
  </div>;
}

function ListDemo({ rows, query, setQuery, onSelect, label }: { rows: Array<{ id: string; name: string; product: string; date: string; amount: number; status: string }>; query: string; setQuery: (value: string) => void; onSelect: (index: number) => void; label: string }) {
  return <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-[#E5E7EB] p-4 sm:flex-row"><div className="relative flex-1"><svg className="absolute left-3 top-3.5 h-5 w-5 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></svg><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`${label}を検索`} className="h-12 w-full rounded-xl border border-[#E5E7EB] bg-[#F8FAFC] pl-11 pr-4 text-sm outline-none focus:border-[#2563EB]" /></div><button onClick={() => alert(`${label}の登録フォームを開きます（デモ）`)} className="rounded-xl bg-[#2563EB] px-5 py-3 text-sm font-bold text-white">＋ 新規登録</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#F8FAFC] text-xs font-bold text-slate-500"><tr><th className="px-5 py-4">管理番号</th><th className="px-5 py-4">対象・顧客</th><th className="px-5 py-4">商品・内容</th><th className="px-5 py-4">日付</th><th className="px-5 py-4">金額</th><th className="px-5 py-4">状態</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((row, index) => <tr key={row.id} onClick={() => onSelect(index)} className="cursor-pointer hover:bg-blue-50/40"><td className="px-5 py-4 text-sm font-bold text-[#2563EB]">{row.id}</td><td className="px-5 py-4 text-sm font-bold">{row.name}</td><td className="px-5 py-4 text-sm text-slate-600">{row.product}</td><td className="px-5 py-4 text-sm text-slate-500">{row.date}</td><td className="px-5 py-4 text-sm font-bold">¥{row.amount.toLocaleString()}</td><td className="px-5 py-4"><StatusBadge tone={row.status === "完了" ? "green" : row.status === "確認待ち" ? "red" : "amber"}>{row.status}</StatusBadge></td></tr>)}</tbody></table></div></section>;
}

function FormDemo({ screen, message, setMessage }: { screen: DemoScreen; message: string; setMessage: (value: string) => void }) {
  return <div className="grid gap-6 xl:grid-cols-[1fr_340px]"><form onSubmit={(event) => { event.preventDefault(); setMessage(`${screen.label}をデモ登録しました`); }} className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="font-bold">基本情報</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">対象顧客<input required defaultValue="山田 花子" className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal outline-none focus:border-[#2563EB]" /></label><label className="text-sm font-bold">実施日<input required type="date" defaultValue="2026-08-05" className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal outline-none focus:border-[#2563EB]" /></label><label className="text-sm font-bold">商品・区分<select className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal"><option>有明牛乳 900ml</option><option>のむヨーグルト</option><option>その他</option></select></label><label className="text-sm font-bold">担当者<select className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal"><option>佐藤 美咲</option><option>田中 悠斗</option></select></label><label className="text-sm font-bold sm:col-span-2">備考<textarea className="mt-2 h-28 w-full rounded-xl border border-[#E5E7EB] p-4 font-normal" placeholder={`${screen.label}に関するメモ`} /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" className="rounded-xl border border-[#E5E7EB] px-5 py-3 text-sm font-bold text-slate-500">下書き保存</button><button className="rounded-xl bg-[#2563EB] px-5 py-3 text-sm font-bold text-white">登録する</button></div></form><aside className="rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><h2 className="font-bold text-blue-800">入力内容の確認</h2><p className="mt-3 text-sm leading-6 text-blue-700">この画面は操作確認用です。登録内容は外部へ送信されません。</p>{message && <div className="mt-5 rounded-xl bg-white p-4 text-sm font-bold text-emerald-700 shadow-sm">✓ {message}</div>}</aside></div>;
}

function ReportDemo({ screen, preview, setPreview, rows }: { screen: DemoScreen; preview: boolean; setPreview: (value: boolean) => void; rows: Array<{ id: string; name: string; product: string; date: string; amount: number; status: string }> }) {
  return <div className="space-y-6"><section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="font-bold">{screen.label}の出力条件</h2><div className="mt-5 grid gap-5 md:grid-cols-3"><label className="text-sm font-bold">対象日<input type="date" defaultValue="2026-08-05" className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal" /></label><label className="text-sm font-bold">コース<select className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal"><option>すべてのコース</option><option>Aコース</option><option>Bコース</option></select></label><label className="text-sm font-bold">出力順<select className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal"><option>配送順</option><option>顧客番号順</option></select></label></div><div className="mt-5 flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" defaultChecked /> 電話番号を表示</label><label className="flex items-center gap-2"><input type="checkbox" defaultChecked /> 配送メモを表示</label><label className="flex items-center gap-2"><input type="checkbox" /> 休配を含む</label></div><div className="mt-6 flex justify-end gap-3"><button onClick={() => setPreview(true)} className="rounded-xl border border-[#2563EB] px-5 py-3 text-sm font-bold text-[#2563EB]">プレビュー</button><button onClick={() => window.print()} className="rounded-xl bg-[#2563EB] px-5 py-3 text-sm font-bold text-white">印刷・PDF</button></div></section>{preview && <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{screen.label}</h2><p className="mt-1 text-xs text-slate-400">2026年8月5日・全コース</p></div><StatusBadge tone="blue">プレビュー</StatusBadge></div><table className="mt-5 w-full text-left text-sm"><thead className="border-y border-[#E5E7EB] bg-[#F8FAFC]"><tr><th className="p-3">No.</th><th className="p-3">顧客</th><th className="p-3">商品</th><th className="p-3">数量</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((row, index) => <tr key={row.id}><td className="p-3">{index + 1}</td><td className="p-3 font-bold">{row.name}</td><td className="p-3">{row.product}</td><td className="p-3">{index + 1}本</td></tr>)}</tbody></table></section>}</div>;
}

function AnalysisDemo({ screen }: { screen: DemoScreen }) {
  const values = [72, 88, 64, 93, 78];
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["対象件数", "1,284", "+4.2%"], ["当月実績", "¥5.08M", "+8.1%"], ["平均単価", "¥3,956", "+1.4%"], ["前月比較", "104.8%", "良好"]].map(([label, value, note]) => <div key={label} className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p><p className="mt-2 text-xs font-bold text-emerald-600">{note}</p></div>)}</div><section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">{screen.label}の推移</h2><p className="mt-1 text-xs text-slate-400">直近5か月のデモデータ</p></div><select className="rounded-lg border border-[#E5E7EB] px-3 py-2 text-xs font-bold"><option>月次</option><option>週次</option></select></div><div className="mt-8 flex h-64 items-end justify-around gap-4 border-b border-slate-200 px-4">{values.map((value, index) => <div key={value} className="flex h-full flex-1 flex-col justify-end"><div className="mb-2 text-center text-xs font-bold text-[#2563EB]">{value}</div><div className="rounded-t-lg bg-[#2563EB] transition-all" style={{ height: `${value}%` }} /><p className="mt-3 text-center text-xs text-slate-400">{index + 4}月</p></div>)}</div></section><section className="rounded-2xl border border-[#E5E7EB] bg-white p-6"><h2 className="font-bold">確認ポイント</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{["本社営業所が全体の61%を占めています", "前月より新規件数が8件増加しています", "金曜日の実績が最も高くなっています"].map((text) => <div key={text} className="rounded-xl bg-[#F8FAFC] p-4 text-sm leading-6 text-slate-600">{text}</div>)}</div></section></div>;
}

function StatusDemo({ screen, done, setDone }: { screen: DemoScreen; done: boolean; setDone: (value: boolean) => void }) {
  const steps = ["データ確認", "対象抽出", "処理実行", "結果確認"];
  return <div className="grid gap-6 xl:grid-cols-[1fr_340px]"><section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="font-bold">{screen.label}の処理状況</h2><div className="mt-6 space-y-3">{steps.map((step, index) => <div key={step} className="flex items-center gap-4 rounded-xl border border-[#E5E7EB] p-4"><span className={`flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold ${done || index < 2 ? "bg-emerald-100 text-emerald-700" : index === 2 ? "bg-blue-100 text-blue-700" : "bg-slate-100 text-slate-400"}`}>{done || index < 2 ? "✓" : index + 1}</span><div className="flex-1"><p className="text-sm font-bold">{step}</p><p className="mt-1 text-xs text-slate-400">{done || index < 2 ? "完了" : index === 2 ? "実行可能" : "待機中"}</p></div></div>)}</div></section><aside className="rounded-2xl border border-[#E5E7EB] bg-white p-6"><h2 className="font-bold">処理を実行</h2><p className="mt-3 text-sm leading-6 text-slate-500">デモでは実データを変更せず、処理完了までの流れを確認できます。</p><button onClick={() => setDone(true)} disabled={done} className="mt-6 w-full rounded-xl bg-[#2563EB] py-3 text-sm font-bold text-white disabled:bg-emerald-500">{done ? "✓ デモ処理完了" : "デモ処理を実行"}</button></aside></div>;
}
