"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { PageHeading, StatusBadge } from "@/components/page-heading";
import { useDemoOffice } from "@/lib/demo-office";
import type { DemoProduct, DemoScreen } from "@/lib/product-navigation";
import { ProductLogo } from "@/components/product-logo";

const sampleNames = ["山田 花子", "鈴木 一郎", "高橋 悦子", "伊藤 健二", "渡辺 直子"];
const sampleProducts = ["有明牛乳 900ml", "のむヨーグルト", "低脂肪乳 900ml", "宅配専用コーヒー", "乳酸菌飲料セット"];

export function ProductDemoScreen({ product, screen }: { product: DemoProduct; screen: DemoScreen }) {
  const { office } = useDemoOffice();
  const [query, setQuery] = useState("");
  const [selectedRow, setSelectedRow] = useState<number | null>(null);
  const [message, setMessage] = useState("");
  const [preview, setPreview] = useState(false);
  const [processDone, setProcessDone] = useState(false);
  const [dashboardMonth, setDashboardMonth] = useState("2026-08");

  const rows = useMemo(() => sampleNames.map((name, index) => ({
    id: `${product.id.toUpperCase()}-${String(index + 241).padStart(4, "0")}`,
    name,
    product: sampleProducts[index],
    date: `2026/08/${String(index + 1).padStart(2, "0")}`,
    amount: 1280 + index * 460,
    status: index === 0 ? "確認待ち" : index === 1 ? "処理中" : "完了",
  })).filter((row) => `${row.id}${row.name}${row.product}`.toLowerCase().includes(query.toLowerCase())), [product.id, query]);

  return <div className={`mx-auto max-w-7xl ${product.id === "selmo" ? "selmo-theme" : ""}`}>
    <div className="mb-3 flex items-center gap-2 text-xs font-bold text-slate-400"><ProductLogo product={product} size={20} /><span className="font-logo text-[10px] font-normal text-[#0F172A]">{product.name}<span className={product.dotColor}>.</span></span><span>/</span><span>{screen.label}</span></div>
    <PageHeading title={screen.label} description={`${office.name}・${screen.description}`} action={product.id === "selmo" && screen.slug === "dashboard" ? <label className="flex items-center gap-3 rounded-xl border border-[#E5E7EB] bg-white px-4 py-2.5 shadow-sm"><span className="text-xs font-bold text-slate-400">対象月</span><input type="month" value={dashboardMonth} onChange={(event) => setDashboardMonth(event.target.value)} className="bg-transparent text-sm font-bold outline-none" /></label> : <span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">操作デモ</span>} />
    {screen.slug === "meetings" && <SalesHistoryDemo />}
    {screen.kind === "list" && screen.slug !== "meetings" && <ListDemo rows={rows} query={query} setQuery={setQuery} onSelect={setSelectedRow} label={screen.label} />}
    {screen.slug === "meeting-upload" && <MeetingUploadDemo message={message} setMessage={setMessage} />}
    {screen.slug === "speaker-separation" && <SpeakerSeparationDemo />}
    {screen.slug === "roleplay" && <RoleplayScenarioDemo />}
    {screen.slug === "roleplay-session" && <RoleplaySessionDemo />}
    {screen.kind === "form" && !["meeting-upload", "speaker-separation", "roleplay", "roleplay-session"].includes(screen.slug) && <FormDemo screen={screen} message={message} setMessage={setMessage} />}
    {screen.kind === "report" && <ReportDemo screen={screen} preview={preview} setPreview={setPreview} rows={rows} />}
    {screen.slug === "meeting-analysis" && <MeetingAnalysisDemo />}
    {screen.slug === "roleplay-results" && <RoleplayResultsDemo />}
    {product.id === "selmo" && screen.slug === "dashboard" && <SelmoDashboardDemo targetMonth={dashboardMonth} />}
    {screen.kind === "analysis" && !(product.id === "selmo" && screen.slug === "dashboard") && !["meeting-analysis", "roleplay-results"].includes(screen.slug) && <AnalysisDemo screen={screen} />}
    {screen.kind === "status" && <StatusDemo screen={screen} done={processDone} setDone={setProcessDone} />}
    {selectedRow !== null && <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/30" onClick={() => setSelectedRow(null)}><aside className="h-full w-full max-w-md bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[#2563EB]">{rows[selectedRow]?.id}</p><h2 className="mt-2 text-xl font-bold">{screen.label}の詳細</h2></div><button onClick={() => setSelectedRow(null)} className="rounded-lg bg-slate-100 p-2">✕</button></div><div className="mt-6 space-y-4">{[["対象", rows[selectedRow]?.name], ["商品・内容", rows[selectedRow]?.product], ["処理日", rows[selectedRow]?.date], ["金額", `¥${rows[selectedRow]?.amount.toLocaleString()}`], ["状態", rows[selectedRow]?.status]].map(([label, value]) => <div key={label} className="border-b border-[#E5E7EB] pb-4"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1.5 text-sm font-semibold">{value}</p></div>)}</div><button onClick={() => { setSelectedRow(null); setMessage("デモ更新しました"); }} className="mt-7 w-full rounded-xl bg-[#2563EB] py-3 text-sm font-bold text-white">編集する</button></aside></div>}
    {message && screen.kind !== "form" && <div className="fixed bottom-6 right-6 rounded-xl bg-[#0F172A] px-5 py-3 text-sm font-bold text-white shadow-xl">{message}</div>}
  </div>;
}

function MeetingUploadDemo({ message, setMessage }: { message: string; setMessage: (value: string) => void }) {
  const router = useRouter();
  const [log, setLog] = useState("");
  const [customerType, setCustomerType] = useState("新規");
  return <form onSubmit={(event) => { event.preventDefault(); setMessage("商談ログを保存しました（デモ）"); router.push("/selmo/speaker-separation"); }}>
    <div className="grid items-stretch gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(420px,0.9fr)]">
      <section className="flex h-full flex-col overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm">
        <div className="border-b border-[#E5E7EB] px-6 py-5"><p className="font-bold">アップロード方法</p><p className="mt-1 text-xs text-slate-500">商談や打ち合わせのログを直接貼り付けて登録します。</p></div>
        <div className="flex flex-1 flex-col p-6"><div className="flex items-end justify-between"><label htmlFor="transcript" className="text-sm font-bold">商談ログ</label><span className="text-xs font-medium text-slate-400">{log.length.toLocaleString()}文字</span></div><textarea id="transcript" name="transcript" value={log} onChange={(event) => setLog(event.target.value)} className="mt-2 min-h-[600px] w-full flex-1 resize-none rounded-xl border border-[#DCE3ED] bg-[#F8FAFC] p-4 text-sm leading-7 outline-none transition focus:border-[#2563EB] focus:bg-white focus:ring-4 focus:ring-blue-50" placeholder={'商談や打ち合わせのログを貼り付けてください。\n\n例）\n営業：本日はお時間をいただきありがとうございます。\nお客様：よろしくお願いします。'} /></div>
      </section>

      <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm">
        <div className="border-b border-[#E5E7EB] px-6 py-5"><h2 className="font-bold">打ち合わせ情報</h2></div>
        <div className="space-y-5 p-6">
          <label className="block text-sm font-bold">予定<select name="schedule" className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] bg-white px-4 font-normal outline-none focus:border-[#2563EB]"><option>予定を選択しない</option><option>山田様 新規提案</option><option>株式会社有明 定例会</option></select></label>
          <label className="block text-sm font-bold">顧客名 / 会社名<input name="customer" placeholder="空欄なら自動で仮タイトルを設定" className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] px-4 font-normal outline-none focus:border-[#2563EB] focus:ring-4 focus:ring-blue-50" /></label>
          <label className="block text-sm font-bold">住所<input name="address" placeholder="例：佐賀県神埼郡吉野ヶ里町吉田1234" autoComplete="street-address" className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] px-4 font-normal outline-none focus:border-[#2563EB]" /></label>
          <label className="block text-sm font-bold">実施日時<span className="text-[#EF4444]">*</span><input name="startedAt" required type="datetime-local" defaultValue="2026-08-12T22:40" min="2026-08-01T00:00" max="2026-08-31T23:59" className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] px-4 font-normal outline-none focus:border-[#2563EB]" /><span className="mt-1.5 block text-xs font-normal leading-5 text-slate-500">実施日時は今月内のみ選択できます。毎月1日に選択可能な月が切り替わります。</span></label>
          <label className="block text-sm font-bold">終了時間<span className="text-[#EF4444]">*</span><input name="endedAt" required type="time" defaultValue="23:40" className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] px-4 font-normal outline-none focus:border-[#2563EB]" /><span className="mt-1.5 block text-xs font-normal leading-5 text-slate-500">ログの終了時刻を入力してください。実施日時の1時間後を自動入力します。</span></label>
          <label className="block text-sm font-bold">商材タイプ<span className="text-[#EF4444]">*</span><select name="productType" required className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] bg-white px-4 font-normal outline-none focus:border-[#2563EB]"><option>commo.</option><option>milmo.</option><option>selmo.</option></select></label>
          <fieldset><legend className="text-sm font-bold">顧客区分<span className="text-[#EF4444]">*</span></legend><div className="mt-2 grid grid-cols-2 gap-2">{["新規", "既存"].map((type) => <button key={type} type="button" onClick={() => setCustomerType(type)} className={`h-11 rounded-xl border text-sm font-bold transition ${customerType === type ? "border-[#2563EB] bg-yellow-50 text-yellow-900" : "border-[#DCE3ED] bg-white text-slate-500"}`}>{type}</button>)}</div><input type="hidden" name="customerType" value={customerType} /></fieldset>
          <label className="block text-sm font-bold">商談目的<span className="text-[#EF4444]">*</span><select name="purpose" required className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] bg-white px-4 font-normal outline-none focus:border-[#2563EB]"><option>新規契約</option><option>クロスセル（商品追加）</option><option>アップセル（本数・プラン変更）</option><option>休止・解約防止</option><option>既存顧客フォロー</option><option>再契約のご提案</option><option>紹介依頼</option><option>その他</option></select></label>
          <label className="block text-sm font-bold">成約/失注ステータス<span className="text-[#EF4444]">*</span><select name="result" required className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] bg-white px-4 font-normal outline-none focus:border-[#2563EB]"><option>検討中</option><option>成約</option><option>失注</option><option>保留</option></select></label>
          <label className="block text-sm font-bold">営業メモ<textarea name="memo" className="mt-2 h-28 w-full resize-y rounded-xl border border-[#DCE3ED] p-4 font-normal outline-none focus:border-[#2563EB]" placeholder="商談中に気になったこと、次回確認したいことなど" /></label>
          <div className="border-t border-[#E5E7EB] pt-5"><button type="submit" className="w-full rounded-xl bg-[#2563EB] px-7 py-3.5 text-sm font-bold shadow-sm transition hover:bg-blue-700">商談ログを保存して分析</button></div>
        </div>
      </section>
    </div>
    {message && <div className="fixed bottom-6 right-6 rounded-xl bg-[#0F172A] px-5 py-3 text-sm font-bold text-white shadow-xl">✓ {message}</div>}
  </form>;
}

const salesHistoryRows = [
  { id: "SA-20260812-01", type: "営業分析", title: "山田様 新規宅配のご提案", customer: "山田 花子", date: "2026/08/12 22:50", purpose: "新規契約", score: 30, status: "関係構築中", summary: "顧客ニーズの深掘りと、具体的な次回アクションの合意が不足していました。", improvement: "現状・課題・理想の順に質問し、次回確認日まで合意する。", href: "/selmo/meeting-analysis" },
  { id: "RP-20260812-03", type: "ロープレ分析", title: "価格反論への切り返し練習", customer: "AI顧客", date: "2026/08/12 21:30", purpose: "反論対応", score: 71, status: "あと一歩", summary: "価格への懸念に確認質問を返し、本数調整の提案へつなげられました。", improvement: "変更後の費用を示し、次回確認日を具体的に合意する。", href: "/selmo/roleplay-results" },
  { id: "SA-20260811-04", type: "営業分析", title: "鈴木様 クロスセル提案", customer: "鈴木 一郎", date: "2026/08/11 15:20", purpose: "クロスセル", score: 78, status: "提案中", summary: "既存商品の利用状況を確認し、ヨーグルト追加の価値を具体的に説明できました。", improvement: "家族の利用意向と初回導入本数を確認する。", href: "/selmo/meeting-analysis" },
  { id: "RP-20260810-02", type: "ロープレ分析", title: "休止・解約防止ロープレ", customer: "AI顧客", date: "2026/08/10 18:10", purpose: "解約防止", score: 84, status: "合格", summary: "解約理由を丁寧に聞き、配送頻度の変更という代替案を提示できました。", improvement: "提案後に顧客の納得度を言葉で確認する。", href: "/selmo/roleplay-results" },
  { id: "SA-20260809-02", type: "営業分析", title: "高橋様 既存契約フォロー", customer: "高橋 悦子", date: "2026/08/09 11:00", purpose: "既存フォロー", score: 66, status: "検討中", summary: "利用状況は確認できましたが、追加ニーズの発見まで進めませんでした。", improvement: "生活変化や家族構成についてオープンクエスチョンを増やす。", href: "/selmo/meeting-analysis" },
];

function SalesHistoryDemo() {
  const router = useRouter();
  const [query, setQuery] = useState("");
  const [type, setType] = useState("すべて");
  const [selected, setSelected] = useState<(typeof salesHistoryRows)[number] | null>(null);
  const shown = salesHistoryRows.filter((row) => (type === "すべて" || row.type === type) && `${row.title}${row.customer}${row.purpose}${row.id}`.includes(query));
  return <>
    <div className="mb-4 grid gap-4 sm:grid-cols-3">{[["分析履歴", `${salesHistoryRows.length}件`], ["営業分析", `${salesHistoryRows.filter((row) => row.type === "営業分析").length}件`], ["ロープレ分析", `${salesHistoryRows.filter((row) => row.type === "ロープレ分析").length}件`]].map(([label, value]) => <div key={label} className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</div>
    <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm"><div className="grid gap-3 border-b border-[#E5E7EB] p-4 sm:grid-cols-[1fr_190px]"><div className="relative"><svg className="absolute left-3 top-3.5 h-5 w-5 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></svg><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="商談名・顧客名・目的で検索" className="h-12 w-full rounded-xl border border-[#DCE3ED] bg-[#F8FAFC] pl-11 pr-4 text-sm outline-none focus:border-[#2563EB]" /></div><select value={type} onChange={(event) => setType(event.target.value)} className="h-12 rounded-xl border border-[#DCE3ED] bg-white px-4 text-sm font-bold"><option>すべて</option><option>営業分析</option><option>ロープレ分析</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-[#F8FAFC] text-xs text-slate-500"><tr><th className="px-5 py-4">分析種別</th><th className="px-5 py-4">商談・練習名</th><th className="px-5 py-4">顧客</th><th className="px-5 py-4">実施日時</th><th className="px-5 py-4">目的</th><th className="px-5 py-4">スコア</th><th className="px-5 py-4">状態</th><th /></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{shown.map((row) => <tr key={row.id} className="hover:bg-yellow-50/40"><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${row.type === "営業分析" ? "bg-yellow-100 text-yellow-800" : "bg-slate-900 text-white"}`}>{row.type}</span></td><td className="px-5 py-4"><p className="text-sm font-bold">{row.title}</p><p className="mt-1 text-[10px] text-slate-400">{row.id}</p></td><td className="px-5 py-4 text-sm">{row.customer}</td><td className="px-5 py-4 text-sm text-slate-500">{row.date}</td><td className="px-5 py-4 text-sm">{row.purpose}</td><td className="px-5 py-4 text-lg font-bold text-[#2563EB]">{row.score}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-2 whitespace-nowrap rounded-full border border-slate-200 bg-white px-2.5 py-1.5 text-[10px] font-bold text-slate-600 shadow-sm"><span className={`h-1.5 w-1.5 rounded-full ${row.status === "合格" ? "bg-emerald-500" : row.status === "提案中" ? "bg-blue-500" : "bg-yellow-400"}`} />{row.status}</span></td><td className="px-5 py-4"><button type="button" onClick={() => setSelected(row)} className="rounded-lg border border-[#DCE3ED] px-3 py-2 text-xs font-bold">詳細</button></td></tr>)}</tbody></table></div></section>
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/35" onMouseDown={() => setSelected(null)}><aside className="h-full w-full max-w-lg overflow-y-auto bg-white shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-start justify-between border-b border-[#E5E7EB] p-6"><div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${selected.type === "営業分析" ? "bg-yellow-100 text-yellow-800" : "bg-slate-900 text-white"}`}>{selected.type}</span><h2 className="mt-3 text-xl font-bold">{selected.title}</h2><p className="mt-1 text-xs text-slate-400">{selected.id}</p></div><button type="button" onClick={() => setSelected(null)} className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-100">×</button></div><div className="space-y-6 p-6"><dl className="grid grid-cols-2 gap-4">{[["顧客", selected.customer], ["実施日時", selected.date], ["目的", selected.purpose], ["状態", selected.status]].map(([label, value]) => <div key={label} className="rounded-xl bg-[#F8FAFC] p-4"><dt className="text-[10px] font-bold text-slate-400">{label}</dt><dd className="mt-2 text-sm font-bold">{value}</dd></div>)}</dl><div className="rounded-2xl bg-yellow-50 p-5 text-center"><p className="text-xs font-bold text-yellow-800">分析スコア</p><p className="mt-2 text-5xl font-bold text-yellow-900">{selected.score}</p><p className="text-xs text-yellow-700">/ 100</p></div><section><h3 className="font-bold">分析サマリー</h3><p className="mt-3 text-sm leading-7 text-slate-600">{selected.summary}</p></section><section><h3 className="font-bold">次回の改善ポイント</h3><p className="mt-3 rounded-xl bg-[#F8FAFC] p-4 text-sm leading-7 text-slate-600">{selected.improvement}</p></section><button type="button" onClick={() => router.push(selected.href)} className="w-full rounded-xl bg-[#2563EB] px-5 py-3.5 text-sm font-bold">分析結果を詳しく見る</button></div></aside></div>}
  </>;
}

const speakerBlocks = [
  { speaker: "営業", role: "営業", initial: "営", text: "本日はお時間をいただきありがとうございます。現在ご利用中の商品について、率直なご感想を伺えますか？" },
  { speaker: "話者2", role: "お客様", initial: "顧", text: "牛乳は家族みんなで飲んでいます。週2回届けてもらえるので助かっています。" },
  { speaker: "営業", role: "営業", initial: "営", text: "ありがとうございます。今回は新しく、毎日の健康をサポートするヨーグルトもご案内しています。" },
  { speaker: "話者2", role: "お客様", initial: "顧", text: "ヨーグルトも気になっています。どのくらいの頻度で届くのでしょうか？" },
  { speaker: "営業", role: "営業", initial: "営", text: "牛乳と同じ曜日に週2回、1本ずつから始められます。まずはお試しで追加することもできます。" },
  { speaker: "話者2", role: "お客様", initial: "顧", text: "それなら負担も少なそうですね。家族にも相談してみたいです。" },
  { speaker: "営業", role: "営業", initial: "営", text: "ぜひご相談ください。来週の配達時に改めてご意向を確認させていただきます。" },
  { speaker: "話者2", role: "お客様", initial: "顧", text: "分かりました。来週までに決めておきます。" },
];

function SpeakerSeparationDemo() {
  const router = useRouter();
  const [query, setQuery] = useState("");
  const [speaker, setSpeaker] = useState("すべての話者");
  const [blocks, setBlocks] = useState(speakerBlocks);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [draftText, setDraftText] = useState("");
  const [draftSpeaker, setDraftSpeaker] = useState("");
  const shown = blocks.map((block, index) => ({ block, index })).filter(({ block }) => (speaker === "すべての話者" || block.speaker === speaker) && `${block.speaker}${block.role}${block.text}`.includes(query));
  const beginEdit = (index: number) => { setEditingIndex(index); setDraftText(blocks[index].text); setDraftSpeaker(blocks[index].speaker); };
  const saveEdit = () => { if (editingIndex === null) return; const role = draftSpeaker === "営業" ? "営業" : draftSpeaker === "話者2" ? "お客様" : draftSpeaker; const initial = draftSpeaker === "営業" ? "営" : draftSpeaker === "話者2" ? "顧" : draftSpeaker === "同席者" ? "同" : "不"; setBlocks((current) => current.map((block, index) => index === editingIndex ? { ...block, speaker: draftSpeaker, role, initial, text: draftText } : block)); setEditingIndex(null); };
  return <div className="space-y-5">
    <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm">
      <div className="flex flex-col gap-4 border-b border-[#E5E7EB] p-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">商談ログ</h2><p className="mt-1 text-xs text-slate-500">話者を確認し、必要に応じて修正してください。</p></div><button type="button" onClick={() => router.push("/selmo/meeting-analysis")} className="rounded-xl bg-[#2563EB] px-6 py-3 text-sm font-bold shadow-sm">AI分析を開始</button></div>
      <dl className="grid gap-px bg-[#E5E7EB] sm:grid-cols-3"><div className="bg-white p-5"><dt className="text-xs font-bold text-slate-400">商談名</dt><dd className="mt-2 text-sm font-bold">未設定_20260812_2250</dd></div><div className="bg-white p-5"><dt className="text-xs font-bold text-slate-400">日時</dt><dd className="mt-2 text-sm font-bold">2026/08/12(水) 22:50 - 23:50</dd></div><div className="bg-white p-5"><dt className="text-xs font-bold text-slate-400">同席者</dt><dd className="mt-2 text-sm font-bold">未設定</dd></div></dl>
      <p className="border-t border-[#E5E7EB] bg-[#F8FAFC] px-6 py-3 text-xs text-slate-500">商談ログ貼り付けで登録されたため、音声ファイルはありません。</p>
    </section>

    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["営業", "4件"], ["話者2", "4件"], ["同席者", "0件"], ["不明", "0件"]].map(([label, count], index) => <div key={label} className={`rounded-xl border bg-white p-4 ${index < 2 ? "border-yellow-200" : "border-[#E5E7EB]"}`}><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{count}</p></div>)}</div>

    <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm">
      <div className="grid gap-3 border-b border-[#E5E7EB] p-4 sm:grid-cols-[1fr_200px]"><div className="relative"><svg className="absolute left-3 top-3.5 h-5 w-5 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></svg><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="キーワードを検索" className="h-12 w-full rounded-xl border border-[#DCE3ED] bg-[#F8FAFC] pl-11 pr-4 text-sm outline-none focus:border-[#2563EB]" /></div><select value={speaker} onChange={(event) => setSpeaker(event.target.value)} className="h-12 rounded-xl border border-[#DCE3ED] bg-white px-4 text-sm font-bold"><option>すべての話者</option><option>営業</option><option>話者2</option></select></div>
      <div className="divide-y divide-[#E5E7EB]">{shown.map(({ block, index }) => editingIndex === index ? <article key={`edit-${index}`} className="grid gap-4 bg-yellow-50/30 p-5 sm:grid-cols-[130px_1fr]">
        <div className="rounded-xl bg-[#F8FAFC] p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold tracking-widest text-slate-400">{String(index + 1).padStart(3, "0")}</p><span className="h-5 w-5 rounded border border-slate-300 bg-white" /></div><select value={draftSpeaker} onChange={(event) => setDraftSpeaker(event.target.value)} className="mt-5 h-11 w-full rounded-xl border border-yellow-300 bg-yellow-50 px-3 text-sm font-bold outline-none"><option>営業</option><option>話者2</option><option>同席者</option><option>不明</option></select><p className="mt-3 text-[10px] font-bold text-slate-400">推定／編集</p></div>
        <div><textarea value={draftText} onChange={(event) => setDraftText(event.target.value)} className="min-h-32 w-full resize-y rounded-xl border border-[#DCE3ED] bg-white p-4 text-sm leading-7 outline-none focus:border-[#2563EB]" /><div className="mt-3"><p className="text-xs font-bold text-slate-500">話者区分</p><div className="mt-2 flex flex-wrap gap-2">{[["営業", "営業"], ["話者2", "顧客"], ["同席者", "同席者"], ["不明", "不明"]].map(([value, label]) => <button key={value} type="button" onClick={() => setDraftSpeaker(value)} className={`rounded-full px-4 py-2 text-xs font-bold ${draftSpeaker === value ? "bg-[#2563EB]" : "bg-slate-100 text-slate-500"}`}>{label}</button>)}</div></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setEditingIndex(null)} className="rounded-lg border border-[#DCE3ED] bg-white px-4 py-2 text-xs font-bold text-slate-600">キャンセル</button><button type="button" onClick={saveEdit} className="rounded-lg bg-[#2563EB] px-5 py-2 text-xs font-bold">保存する</button></div></div>
      </article> : <article key={`${block.speaker}-${index}`} className="grid gap-4 p-5 sm:grid-cols-[52px_1fr_auto]"><div><p className="mb-2 text-center text-[10px] font-bold text-slate-400">{String(index + 1).padStart(3, "0")}</p><span className={`flex h-10 w-10 items-center justify-center rounded-full text-sm font-bold ${block.role === "お客様" ? "bg-blue-700 text-white" : "bg-yellow-100 text-yellow-900"}`}>{block.initial}</span></div><div><div className="flex items-center gap-2"><p className="text-sm font-bold">{block.speaker}</p><span className={`rounded px-2 py-0.5 text-[10px] font-bold ${block.role === "お客様" ? "bg-blue-50 text-blue-700" : "bg-slate-100 text-slate-500"}`}>{block.role}</span></div><p className="mt-2 text-sm leading-7 text-slate-700">{block.text}</p></div><div><button type="button" onClick={() => beginEdit(index)} className="rounded-md border border-[#DCE3ED] px-2.5 py-1.5 text-[11px] font-bold">修正</button></div></article>)}</div>
      <div className="flex flex-col gap-3 border-t border-[#E5E7EB] bg-[#F8FAFC] px-5 py-4 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>表示中：{shown.length ? `1〜${shown.length}` : "0"}ブロック（全{shown.length}ブロック）</span><button type="button" disabled className="rounded-lg border border-[#DCE3ED] bg-white px-4 py-2 font-bold text-slate-400 disabled:opacity-60">前へ</button></div>
    </section>
  </div>;
}

const analysisPoints = ["顧客はリピーター育成やOTA手数料削減に興味を示した。", "営業の発話が一方的で、顧客のニーズに対する深掘りが不足していた。", "具体的な次のステップの合意が薄かった。"];
const nextActions = ["導入事例の送付", "お見積りの提出", "運用フローのご提案"];

function AnalysisBulletList({ checked = false }: { checked?: boolean }) {
  return <ul className="mt-4 space-y-3">{analysisPoints.map((point) => <li key={point} className="flex gap-3 text-sm leading-6 text-slate-600"><span className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[10px] font-bold ${checked ? "bg-emerald-100 text-emerald-700" : "bg-yellow-100 text-yellow-800"}`}>{checked ? "✓" : "•"}</span>{point}</li>)}</ul>;
}

function AnalysisActionList() {
  return <ol className="mt-4 space-y-3">{nextActions.map((action, index) => <li key={action} className="flex items-center gap-3 rounded-xl bg-[#F8FAFC] p-3 text-sm font-bold"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#2563EB] text-xs">{index + 1}</span>{action}</li>)}</ol>;
}

function MeetingAnalysisDemo() {
  const evaluations = [["ヒアリング", "顧客のニーズを深掘りするヒアリングが不足している。"], ["課題深掘り", "顧客の課題に対する深掘りが不十分で、具体的な提案ができていない。"], ["提案接続", "営業の提案が顧客のニーズに接続しておらず、具体性が欠けている。"], ["反論対応", "顧客の懸念に対する反論対応が不十分で、次のステップの合意が薄い。"], ["クロージング", "次回のアクションや具体的な合意が得られていない。"]];
  const feedback = [["👍", "良かった点", ["会話の入り方が自然で関係構築ができている", "提案の方向性は相手に伝わっている", "質問のキャッチボールができている"]], ["⚠️", "改善ポイント", ["価格や費用の説明がやや曖昧だった", "比較検討している他社との差分確認が少ない", "次回アクションの説明が曖昧だった"]], ["💡", "次回意識すること", ["導入後のイメージを具体的に共有する", "決裁プロセスやスケジュールを確認する", "ROIや定量的な効果を提示する"]]] as const;
  return <div className="space-y-6">
    <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E5E7EB] p-6"><div><div className="flex items-center gap-2"><h2 className="text-2xl font-bold">AI営業分析</h2><span className="rounded-full bg-yellow-100 px-2.5 py-1 text-[10px] font-bold text-yellow-800">β版</span></div><p className="mt-2 text-xs text-slate-500">分析結果は目安です</p></div></div><div className="p-6"><p className="text-xs font-bold text-[#2563EB]">要点サマリー</p><p className="mt-3 max-w-5xl text-sm leading-7 text-slate-700">商談では、顧客がリピーター育成やOTA手数料削減に関心を示したが、営業の提案に対する具体的な返答や次のステップの合意が不足していた。顧客のニーズに対する深掘りが不十分で、営業の発話が一方的になりがちだった。</p></div></section>

    <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><p className="text-xs font-bold text-slate-400">商談ステータス</p><p className="mt-3 text-xl font-bold">関係構築中</p><p className="mt-3 text-sm leading-6 text-slate-500">顧客との信頼関係を構築する段階であり、具体的な提案や次のステップの合意が不足している。</p></section><section className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><p className="text-xs font-bold text-slate-400">温度感</p><div className="mt-3 flex gap-1 text-xl text-yellow-400"><span>★</span><span className="text-slate-200">★★★★</span></div><p className="mt-3 text-sm leading-6 text-slate-500">顧客の質問や懸念が明確に示されておらず、営業との対話が浅い。</p></section><section className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><div className="flex items-end justify-between"><p className="text-xs font-bold text-slate-400">検討度</p><p className="text-2xl font-bold">30<span className="ml-1 text-sm text-slate-400">%</span></p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[30%] rounded-full bg-[#2563EB]" /></div><p className="mt-3 text-sm leading-6 text-slate-500">顧客のニーズや課題が具体的に掘り下げられておらず、商材の提案も不十分。</p></section></div>

    <div className="grid gap-4 lg:grid-cols-2">{["現在の運用", "抱えている課題", "求めていること"].map((title) => <section key={title} className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><h3 className="font-bold">{title}</h3><AnalysisBulletList /></section>)}<section className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><h3 className="font-bold">次回アクション</h3><AnalysisActionList /></section></div>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">商談評価サマリー</h2><div className="mt-5 grid gap-3 lg:grid-cols-5">{evaluations.map(([label, description]) => <div key={label} className="rounded-xl border border-[#E5E7EB] p-4"><p className="text-sm font-bold">{label}</p><p className="mt-3 text-2xl font-bold text-[#2563EB]">30<span className="text-xs text-slate-400"> /100</span></p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[30%] bg-[#2563EB]" /></div><p className="mt-3 text-xs leading-5 text-slate-500">{description}</p></div>)}</div></section>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">AIによる商談ポイント分析</h2><p className="mt-1 text-sm text-slate-500">顧客視点の要点と、次回の進め方につながるポイントを整理しています。</p><div className="mt-6 grid gap-4 lg:grid-cols-2">{["顧客の課題（検出）", "顧客の要望（検出）", "顧客の不安・懸念（検出）"].map((title) => <div key={title} className="rounded-xl bg-[#F8FAFC] p-5"><h3 className="font-bold">{title}</h3><AnalysisBulletList checked /></div>)}<div className="rounded-xl bg-[#F8FAFC] p-5"><h3 className="font-bold">次回アクション（検出）</h3><AnalysisActionList /></div></div></section>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">商談ログインサイト</h2><p className="mt-1 text-sm text-slate-500">確定した会話ブロックから、分析時に確認したい言葉をまとめています。</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-[#E5E7EB] p-5"><p className="text-xs font-bold text-slate-400">頻出ワード</p><div className="mt-3 flex items-center justify-between"><p className="font-bold">1　テスト</p><span className="rounded-full bg-yellow-100 px-3 py-1 text-xs font-bold">8回</span></div></div><div className="rounded-xl border border-[#E5E7EB] p-5"><p className="text-xs font-bold text-slate-400">顧客側の頻出ワード</p><div className="mt-3 flex items-center justify-between"><p className="font-bold">1　テスト</p><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-700">4回</span></div></div></div><div className="mt-4 rounded-xl bg-[#F8FAFC] p-5"><p className="font-bold">注目ワード</p><p className="mt-2 text-sm text-slate-500">課題・不安・価値・次回アクションに関わる言葉を表示します。</p></div></section>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">AIからのフィードバック</h2><div className="mt-5 grid gap-4 lg:grid-cols-3">{feedback.map(([icon, title, points]) => <div key={title} className="rounded-xl border border-[#E5E7EB] p-5"><div className="flex items-center gap-2"><span className="text-xl">{icon}</span><h3 className="font-bold">{title}</h3></div><ul className="mt-4 space-y-3">{points.map((point) => <li key={point} className="flex gap-2 text-sm leading-6 text-slate-600"><span>•</span>{point}</li>)}</ul></div>)}</div><p className="mt-6 border-t border-[#E5E7EB] pt-5 text-xs leading-6 text-slate-500">この分析は商談ログをもとにAIが自動で生成しています。顧客の実際の発言を確認しながら、勝ち筋・改善点・次アクションの検討に活用してください。</p></section>
  </div>;
}

function RoleplayScenarioDemo() {
  const router = useRouter();
  const [selected, setSelected] = useState("ヒアリング");
  const [creatorOpen, setCreatorOpen] = useState(false);
  const [extraFields, setExtraFields] = useState(0);
  const scenarios = [
    ["ヒアリング", "顧客の現状や悩みを深掘りし、潜在的なニーズを引き出す練習", "質問力", "初級"],
    ["クロスセル提案", "既存の宅配商品に加えて、新しい商品を自然に提案する練習", "提案接続", "中級"],
    ["価格への反論対応", "価格を理由に迷っている顧客へ、価値を整理して伝える練習", "反論対応", "中級"],
    ["休止・解約防止", "休止や解約を検討している顧客の理由を聞き、継続案を提案する練習", "関係構築", "上級"],
  ];
  return <div className="space-y-6">
    <nav aria-label="ロープレの進行" className="rounded-2xl border border-[#E5E7EB] bg-white px-5 py-4 shadow-sm"><ol className="grid gap-3 sm:grid-cols-3">{[["1", "シナリオ選択"], ["2", "ロープレ中"], ["3", "分析結果"]].map(([number, label], index) => <li key={number} className="flex items-center gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-sm font-bold ${index === 0 ? "bg-[#2563EB]" : "bg-slate-100 text-slate-400"}`}>{number}</span><span className={`text-sm font-bold ${index === 0 ? "text-slate-900" : "text-slate-400"}`}>{label}</span>{index < 2 && <span className="ml-auto hidden text-slate-300 sm:block">→</span>}</li>)}</ol></nav>

    <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-[#E5E7EB] p-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold tracking-[0.18em] text-[#2563EB]">SCENARIOS</p><h2 className="mt-2 text-2xl font-bold">苦手テーマを選択</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">商談・テレアポ分析で見えた弱点を、AI顧客ロープレで自分のペースで集中練習できます。</p></div><button type="button" onClick={() => setCreatorOpen(true)} className="shrink-0 rounded-xl border border-yellow-400 bg-yellow-50 px-5 py-3 text-sm font-bold text-yellow-900">＋ 弱点課題を作成</button></div><div className="grid gap-4 p-6 md:grid-cols-2">{scenarios.map(([title, description, skill, level]) => <button key={title} type="button" onClick={() => setSelected(title)} className={`group rounded-2xl border p-5 text-left transition ${selected === title ? "border-yellow-400 bg-yellow-50 shadow-sm" : "border-[#E5E7EB] hover:border-yellow-300 hover:bg-yellow-50/40"}`}><div className="flex items-start justify-between gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl text-lg ${selected === title ? "bg-[#2563EB]" : "bg-slate-100"}`}>✦</span><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold text-slate-500">{level}</span></div><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><div className="mt-4 flex items-center justify-between"><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-yellow-800">強化：{skill}</span><span className={`text-lg transition ${selected === title ? "translate-x-0 text-yellow-600" : "text-slate-300 group-hover:translate-x-1"}`}>→</span></div></button>)}</div><div className="flex flex-col gap-3 border-t border-[#E5E7EB] bg-[#F8FAFC] p-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-500">選択中：<span className="font-bold text-slate-900">{selected}</span></p><button type="button" onClick={() => router.push("/selmo/roleplay-session")} className="rounded-xl bg-[#2563EB] px-6 py-3 text-sm font-bold shadow-sm">このシナリオで開始</button></div></section>

    {creatorOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/45 p-4" onMouseDown={() => setCreatorOpen(false)}><form onSubmit={(event) => { event.preventDefault(); setCreatorOpen(false); }} onMouseDown={(event) => event.stopPropagation()} className="max-h-[calc(100vh-2rem)] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-[#E5E7EB] bg-white px-6 py-5"><div><h2 className="text-xl font-bold">弱点課題作成</h2><p className="mt-1 max-w-xl text-sm leading-6 text-slate-500">商材・カテゴリーと過去分析から、重点的に反復できる苦手克服シナリオをAI生成できます。</p></div><button type="button" aria-label="閉じる" onClick={() => setCreatorOpen(false)} className="ml-4 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-slate-100 text-lg">×</button></div><div className="space-y-6 p-6">
      <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">商材 <span className="text-red-500">*</span><select required className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] bg-white px-4 font-normal"><option value="">商材を選択</option><option>milmo.</option><option>commo.</option></select></label><label className="text-sm font-bold">カテゴリー <span className="text-red-500">*</span><select required className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] bg-white px-4 font-normal"><option value="">選択してください</option><option>新規契約</option><option>クロスセル</option><option>解約防止</option></select></label></div>
      <label className="block text-sm font-bold">ターゲット層<input placeholder="空欄ならAIが選定" className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] px-4 font-normal" /></label>
      <div><label className="text-sm font-bold">今回つぶしたい苦手<textarea className="mt-2 h-28 w-full resize-y rounded-xl border border-[#DCE3ED] p-4 font-normal" placeholder="例：価格反論を受けると説明が長くなる / 決裁者確認を聞き切れない / 次回アクションを曖昧に終えてしまう" /></label><div className="mt-3 flex flex-wrap gap-2">{["価格反論に対して確認質問と効果訴求で切り返す", "決裁者・社内確認フローを聞き切る", "予算感と費用対効果を確認する", "導入時期と次回アクションを曖昧にせず合意する", "ヒアリング"].map((item) => <button key={item} type="button" className="rounded-full border border-yellow-200 bg-yellow-50 px-3 py-2 text-xs font-bold text-yellow-900">{item}</button>)}</div><button type="button" className="mt-4 w-full rounded-xl bg-slate-900 py-3 text-sm font-bold text-white">AIで弱点課題生成</button></div>
      <div className="border-t border-[#E5E7EB] pt-6"><p className="mb-5 text-xs font-bold tracking-[0.14em] text-slate-400">シナリオ詳細</p><div className="space-y-5"><label className="block text-sm font-bold">タイトル<input placeholder="例：料金反論を効果訴求に切り返す集中練習" className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] px-4 font-normal" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">顧客役職<input placeholder="例：営業部長" className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] px-4 font-normal" /></label><label className="text-sm font-bold">難易度<select defaultValue="難しい" className="mt-2 h-12 w-full rounded-xl border border-[#DCE3ED] bg-white px-4 font-normal"><option>やさしい</option><option>普通</option><option>難しい</option></select></label></div><label className="block text-sm font-bold">概要<textarea className="mt-2 h-24 w-full rounded-xl border border-[#DCE3ED] p-4 font-normal" placeholder="どの苦手テーマを、どの場面で練習するか" /></label><label className="block text-sm font-bold">顧客プロフィール<textarea className="mt-2 h-24 w-full rounded-xl border border-[#DCE3ED] p-4 font-normal" placeholder="業種、課題、検討状況など" /></label><label className="block text-sm font-bold">練習ゴール <span className="text-red-500">*</span><textarea required className="mt-2 h-24 w-full rounded-xl border border-[#DCE3ED] p-4 font-normal" placeholder="例：価格反論に対して、効果・事例・導入後の成果で30秒以内に切り返す" /></label><label className="block text-sm font-bold">想定反論<textarea className="mt-2 h-24 w-full rounded-xl border border-[#DCE3ED] p-4 font-normal" placeholder={'1行に1つ\n例：料金が高い'} /></label><label className="block text-sm font-bold">採点基準<textarea className="mt-2 h-24 w-full rounded-xl border border-[#DCE3ED] p-4 font-normal" placeholder={'1行に1つ\n例：苦手テーマを再現した反論に対して、確認質問を返せている'} /></label></div></div>
      <div className="border-t border-[#E5E7EB] pt-6"><h3 className="font-bold">自由項目</h3><p className="mt-1 text-xs text-slate-500">重点弱点、避けたい癖、合格ラインなどを自由に追加できます。</p>{Array.from({ length: extraFields }, (_, index) => <div key={index} className="mt-3 grid gap-2 sm:grid-cols-2"><input placeholder="項目名" className="h-11 rounded-xl border border-[#DCE3ED] px-3 text-sm" /><input placeholder="内容" className="h-11 rounded-xl border border-[#DCE3ED] px-3 text-sm" /></div>)}<button type="button" onClick={() => setExtraFields((count) => count + 1)} className="mt-4 rounded-xl border border-[#DCE3ED] px-4 py-2.5 text-sm font-bold">＋ 項目を追加</button></div>
    </div><div className="sticky bottom-0 flex justify-end gap-3 border-t border-[#E5E7EB] bg-white px-6 py-4"><button type="button" onClick={() => setCreatorOpen(false)} className="rounded-xl border border-[#DCE3ED] px-5 py-3 text-sm font-bold text-slate-600">キャンセル</button><button type="submit" className="rounded-xl bg-[#2563EB] px-6 py-3 text-sm font-bold">作成する</button></div></form></div>}
  </div>;
}

function RoleplaySessionDemo() {
  const router = useRouter();
  const [recording, setRecording] = useState(false);
  const [turn, setTurn] = useState(2);
  const conversationPairs = [["本日はお時間をいただきありがとうございます。現在のお届け商品について、何かお困りのことはありませんか？", "特に困ってはいませんが、最近少し価格が気になっています。"], ["価格についてですね。どの商品で特に負担を感じていらっしゃいますか？", "牛乳は続けたいのですが、家族が減って余ることも増えました。"], ["ありがとうございます。本数を調整しながら、必要な週だけお届けする方法もあります。", "それなら続けやすそうですね。詳しく教えてください。"]];
  const handleRecord = () => { if (!recording) { setRecording(true); return; } setRecording(false); setTurn((current) => Math.min(current + 1, conversationPairs.length)); };
  return <div className="space-y-5">
    <nav aria-label="ロープレの進行" className="rounded-2xl border border-[#E5E7EB] bg-white px-5 py-4 shadow-sm"><ol className="grid gap-3 sm:grid-cols-3">{[["1", "シナリオ選択"], ["2", "ロープレ中"], ["3", "分析結果"]].map(([number, label], index) => <li key={number} className="flex items-center gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-sm font-bold ${index === 1 ? "bg-[#2563EB]" : "bg-slate-100 text-slate-400"}`}>{number}</span><span className={`text-sm font-bold ${index === 1 ? "text-slate-900" : "text-slate-400"}`}>{label}</span>{index < 2 && <span className="ml-auto hidden text-slate-300 sm:block">→</span>}</li>)}</ol></nav>
    <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm">
      <header className="flex flex-col gap-4 border-b border-[#E5E7EB] p-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold text-yellow-700">commo.</p><h2 className="mt-2 text-2xl font-bold">commo. 新規ロープレ</h2><p className="mt-3 text-sm leading-6 text-slate-500">苦手テーマを自分のペースで集中練習します。録音停止後に文字起こしし、AI顧客が返答します。</p></div><button type="button" onClick={() => router.push("/selmo/roleplay")} className="shrink-0 rounded-xl border border-[#DCE3ED] px-4 py-2.5 text-sm font-bold">苦手テーマ変更</button></header>
      <div className="min-h-[440px] bg-[#F8FAFC] p-5 sm:p-7">{turn === 0 && <div className="rounded-2xl border border-dashed border-[#DCE3ED] bg-white p-6 text-center"><h3 className="font-bold">営業側から開始</h3><p className="mx-auto mt-2 max-w-2xl text-sm leading-7 text-slate-500">下の録音ボタンを押して、練習ゴールの苦手テーマを意識しながら話してください。AIは顧客役として返答します。</p></div>}<div className={`mx-auto max-w-4xl space-y-5 ${turn === 0 ? "mt-6" : ""}`}>{conversationPairs.slice(0, turn).map(([sales, ai], index) => <div key={index} className="space-y-3"><div className="flex justify-end"><div className="max-w-[82%]"><p className="mb-1 text-right text-[10px] font-bold text-slate-400">営業</p><div className="rounded-2xl rounded-br-sm bg-slate-900 px-5 py-3.5 text-sm leading-6 text-white shadow-sm">{sales}</div></div></div><div className="flex justify-start"><div className="max-w-[82%]"><p className="mb-1 text-[10px] font-bold text-yellow-700">AI顧客</p><div className="rounded-2xl rounded-bl-sm bg-yellow-300 px-5 py-3.5 text-sm font-medium leading-6 text-yellow-950 shadow-sm">{ai}</div></div></div></div>)}{recording && <div className="flex justify-end"><div className="flex items-center gap-2 rounded-full bg-red-50 px-4 py-2 text-xs font-bold text-red-600"><span className="h-2 w-2 animate-pulse rounded-full bg-red-500" />録音しています...</div></div>}</div></div>
      <footer className="grid gap-3 border-t border-[#E5E7EB] p-5 lg:grid-cols-[240px_240px_1fr_1fr_1fr]"><button type="button" onClick={handleRecord} className={`rounded-xl px-5 py-3.5 text-sm font-bold text-white ${recording ? "bg-red-600" : "bg-slate-900"}`}>{recording ? "■ 録音を停止" : "◉ 録音して話す"}</button><button type="button" disabled={!turn || recording} onClick={() => router.push("/selmo/roleplay-results")} className="rounded-xl bg-[#2563EB] px-5 py-3.5 text-sm font-bold disabled:cursor-not-allowed disabled:bg-yellow-100 disabled:text-yellow-600">終了して採点</button><div className="rounded-xl border border-[#E5E7EB] bg-[#F8FAFC] px-4 py-3"><p className="text-[10px] font-bold text-slate-400">録音</p><p className="mt-1 text-sm font-bold">{recording ? "録音中" : "--:--"}</p></div><div className="rounded-xl border border-[#E5E7EB] bg-[#F8FAFC] px-4 py-3"><p className="text-[10px] font-bold text-slate-400">状態</p><p className="mt-1 text-sm font-bold">{recording ? "営業が発話中" : turn ? "返答完了" : "待機中"}</p></div><div className="rounded-xl border border-[#E5E7EB] bg-[#F8FAFC] px-4 py-3"><p className="text-[10px] font-bold text-slate-400">発話</p><p className="mt-1 text-sm font-bold">{turn * 2}回</p></div></footer>
    </section>
  </div>;
}

function RoleplayResultsDemo() {
  const router = useRouter();
  const scores = [["ヒアリング", 72, "価格への不安を確認質問で具体化できました。"], ["課題深掘り", 64, "家族構成や余る頻度をもう一段深掘りできると良いです。"], ["提案接続", 82, "本数調整という提案を顧客の悩みに接続できました。"], ["反論対応", 76, "価格の反論に対してすぐ説明せず、質問を返せています。"], ["クロージング", 58, "次回確認日や具体的な合意まで進める必要があります。"]] as const;
  return <div className="space-y-6">
    <nav aria-label="ロープレの進行" className="rounded-2xl border border-[#E5E7EB] bg-white px-5 py-4 shadow-sm"><ol className="grid gap-3 sm:grid-cols-3">{[["1", "シナリオ選択"], ["2", "ロープレ中"], ["3", "分析結果"]].map(([number, label], index) => <li key={number} className="flex items-center gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-sm font-bold ${index === 2 ? "bg-[#2563EB]" : "bg-slate-100 text-slate-400"}`}>{number}</span><span className={`text-sm font-bold ${index === 2 ? "text-slate-900" : "text-slate-400"}`}>{label}</span>{index < 2 && <span className="ml-auto hidden text-slate-300 sm:block">→</span>}</li>)}</ol></nav>

    <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-[#E5E7EB] p-6 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-2xl font-bold">AIロープレ分析</h2><span className="rounded-full bg-yellow-100 px-2.5 py-1 text-[10px] font-bold text-yellow-800">β版</span></div><p className="mt-2 text-xs text-slate-500">分析結果は練習の目安です</p></div><button type="button" onClick={() => router.push("/selmo/roleplay")} className="rounded-xl border border-yellow-400 bg-yellow-50 px-5 py-3 text-sm font-bold text-yellow-900">もう一度練習する</button></div><div className="grid gap-px bg-[#E5E7EB] lg:grid-cols-[220px_1fr]"><div className="flex flex-col items-center justify-center bg-white p-7"><p className="text-xs font-bold text-slate-400">総合スコア</p><p className="mt-2 text-5xl font-bold text-[#2563EB]">71</p><p className="mt-1 text-xs font-bold text-slate-400">/ 100</p></div><div className="bg-white p-7"><p className="text-xs font-bold text-[#2563EB]">評価サマリー</p><p className="mt-3 text-sm leading-7 text-slate-700">価格への懸念に対して確認質問を返し、顧客の状況に合わせた本数調整を提案できました。一方で、家族構成や利用頻度の深掘り、次回アクションの具体的な合意が不足しています。</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">前回比 +8点</span><span className="rounded-full bg-yellow-50 px-3 py-1.5 text-xs font-bold text-yellow-800">難易度：中級</span><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-600">発話 6回</span></div></div></div></section>

    <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><p className="text-xs font-bold text-slate-400">練習テーマ</p><p className="mt-3 text-lg font-bold">価格への反論対応</p><p className="mt-2 text-sm leading-6 text-slate-500">説明を急がず、確認質問と効果訴求で切り返す練習。</p></section><section className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><p className="text-xs font-bold text-slate-400">ゴール達成度</p><div className="mt-3 flex items-end justify-between"><p className="text-2xl font-bold">75%</p><span className="text-xs font-bold text-yellow-700">概ね達成</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-3/4 rounded-full bg-[#2563EB]" /></div></section><section className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><p className="text-xs font-bold text-slate-400">判定</p><p className="mt-3 text-lg font-bold">あと一歩</p><p className="mt-2 text-sm leading-6 text-slate-500">最後に次回確認日まで合意できれば合格ラインです。</p></section></div>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">項目別スコア</h2><div className="mt-5 grid gap-3 lg:grid-cols-5">{scores.map(([label, score, description]) => <div key={label} className="rounded-xl border border-[#E5E7EB] p-4"><p className="text-sm font-bold">{label}</p><p className="mt-3 text-2xl font-bold text-[#2563EB]">{score}<span className="text-xs text-slate-400"> /100</span></p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#2563EB]" style={{ width: `${score}%` }} /></div><p className="mt-3 text-xs leading-5 text-slate-500">{description}</p></div>)}</div></section>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">AIからのフィードバック</h2><div className="mt-5 grid gap-4 lg:grid-cols-3">{[["👍", "良かった点", ["価格の話にすぐ反論せず、困りごとを質問できた", "顧客の状況に合わせて本数調整を提案できた", "落ち着いた言葉で会話を進められた"]], ["⚠️", "改善ポイント", ["余る頻度や現在の本数を具体的に確認できていない", "提案による金額変化を明確に説明できていない", "次回の確認日を決めずに会話を終えている"]], ["💡", "次回意識すること", ["現状・理想・差分の順で質問する", "提案後に顧客の理解と納得を確認する", "最後に誰が・いつ・何をするか合意する"]]].map(([icon, title, items]) => <div key={String(title)} className="rounded-xl border border-[#E5E7EB] p-5"><div className="flex items-center gap-2"><span className="text-xl">{icon}</span><h3 className="font-bold">{title}</h3></div><ul className="mt-4 space-y-3">{(items as string[]).map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-slate-600"><span>•</span>{item}</li>)}</ul></div>)}</div></section>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">会話別フィードバック</h2><p className="mt-1 text-sm text-slate-500">ロープレ中の発話ごとに、評価ポイントを確認できます。</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-500">3ターン</span></div><div className="mt-5 space-y-4">{[["営業", "価格についてですね。どの商品で特に負担を感じていらっしゃいますか？", "確認質問を返せており良い対応です。さらに現在の本数まで聞けると、提案が具体的になります。", "良い"], ["営業", "本数を調整しながら、必要な週だけお届けする方法もあります。", "顧客の悩みに沿った提案です。変更後の費用も一緒に示しましょう。", "良い"], ["営業", "それではご検討ください。", "次回の確認日や連絡方法まで具体的に合意すると、クロージング評価が上がります。", "改善"]].map(([role, text, note, status], index) => <article key={text} className="rounded-xl border border-[#E5E7EB] p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-900 text-xs font-bold text-white">営</span><span className="text-xs font-bold text-slate-500">{role}・{index + 1}</span></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${status === "良い" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{status}</span></div><p className="mt-4 rounded-xl bg-slate-900 px-4 py-3 text-sm leading-6 text-white">{text}</p><p className="mt-3 text-sm leading-6 text-slate-600">{note}</p></article>)}</div></section>
    <p className="text-xs leading-6 text-slate-500">この分析はロープレ中の会話をもとにAIが自動生成しています。実際の営業場面に合わせて、繰り返し練習するテーマの選定に活用してください。</p>
  </div>;
}

function SelmoDashboardDemo({ targetMonth }: { targetMonth: string }) {
  const router = useRouter();
  const focusItems = [["課題ヒアリング", "顧客の発話がテストのみで、具体的なニーズが不明。"], ["価値提案", "営業の発話もテストのみで、具体的な提案がなかった。"], ["反論処理", "顧客がリピーター育成やOTA手数料削減に関心を示したが、営業の提案に対する具体的な返答がなかった。"], ["次回アクション合意", "具体的な次のステップの合意が薄かった。"]];
  const ooda = [["01", "活動状況", [["今週の商談", "1件"], ["未分析", "0件"], ["分析済み", "1件"], ["平均商談時間", "60分"], ["対象月のロープレ", "0回"], ["停滞/要確認", "1件"]]], ["02", "商談の傾向", [["顧客課題", "競合比較・不安"], ["多いステータス", "検討中 1件"], ["失注/停滞", "1件"], ["頻出ワード", "テスト"], ["弱いスキル", "ヒアリング 30点"]]], ["03", "改善テーマ", [["優先項目", "提案前に顧客課題を一度要約する"], ["必ず聞くこと", "蓄積待ち"], ["避けたい流れ", "課題確認前に料金説明へ入る"], ["関連ロープレ", "commo. 新規ロープレ"], ["確認タイミング", "提案前とクロージング前"]]], ["04", "やること", [["商談確認", "未設定_20260812_2250"], ["ロープレ", "commo. 新規ロープレ"], ["ナレッジ", "11件から検索可能"], ["次回準備", "蓄積待ち"]]]] as const;
  const skills = [["ヒアリング", "現状・背景・課題を聞けているか"], ["課題整理", "顧客の言葉で課題を整理できているか"], ["提案力", "商材価値を課題に接続できているか"], ["切り返し", "不安や比較に対して確認できているか"], ["クロージング", "次回日程・宿題・決裁確認まで進めたか"]];
  return <div className="space-y-6" data-period={targetMonth}>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["対象月の商談数", "1件", "対象月にアップロードされた記録"], ["成約率", "0%", "成約データなし"], ["分析済み件数", "1件", "AIサマリー確認済みの件数"], ["AIスコア", "30点", "直近分析の平均値"]].map(([label, value, note]) => <section key={label} className="rounded-2xl border border-[#E5E7EB] bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></section>)}</div>

    <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm"><div className="flex items-end justify-between gap-4 border-b border-[#E5E7EB] p-6"><div><p className="text-xs font-bold tracking-[0.15em] text-[#2563EB]">RECENT</p><h2 className="mt-2 text-xl font-bold">直近商談一覧</h2><p className="mt-1 text-sm text-slate-500">直近5件の商談を表示します。</p></div><button type="button" onClick={() => router.push("/selmo/meetings")} className="text-sm font-bold text-yellow-800">すべて見る →</button></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="bg-[#F8FAFC] text-xs text-slate-500"><tr>{["商談名", "日付", "結果", "AIスコア", "主な改善ポイント", "詳細"].map((heading) => <th key={heading} className="px-5 py-4">{heading}</th>)}</tr></thead><tbody><tr><td className="px-5 py-5 font-bold">未設定_20260812_2250</td><td className="px-5 py-5 text-sm text-slate-500">08/12 22:50</td><td className="px-5 py-5"><span className="rounded-full border border-slate-200 px-2.5 py-1 text-xs font-bold">検討中</span></td><td className="px-5 py-5 text-lg font-bold text-[#2563EB]">30点</td><td className="max-w-md px-5 py-5 text-sm leading-6 text-slate-600">次回は顧客の具体的なニーズを深掘りし、信頼を築くための提案を行いましょう。</td><td className="px-5 py-5"><button type="button" onClick={() => router.push("/selmo/meeting-analysis")} className="rounded-lg border border-[#DCE3ED] px-3 py-2 text-xs font-bold">詳細</button></td></tr></tbody></table></div><p className="border-t border-[#E5E7EB] bg-[#F8FAFC] px-5 py-3 text-xs text-slate-500">最新: 未設定_20260812_2250</p></section>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><p className="text-xs font-bold tracking-[0.15em] text-[#2563EB]">TRAINING FOCUS</p><h2 className="mt-2 text-xl font-bold">商材 × 苦手な部分</h2><p className="mt-1 text-sm text-slate-500">AI営業分析から、商材ごとにロープレで強化すべきテーマを表示します。</p><div className="mt-6 grid gap-4 lg:grid-cols-2">{focusItems.map(([title, description]) => <article key={title} className="rounded-2xl border border-[#E5E7EB] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-yellow-700">commo.</p><h3 className="mt-1 font-bold">{title}</h3></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">1件</span></div><p className="mt-3 min-h-12 text-sm leading-6 text-slate-500">{description}</p><button type="button" onClick={() => router.push("/selmo/roleplay")} className="mt-4 w-full rounded-xl bg-yellow-50 px-4 py-3 text-left text-sm font-bold text-yellow-900">commo.の{title}を鍛えるロープレ <span className="float-right">→</span></button><div className="mt-3 flex gap-4 text-xs text-slate-400"><span>対象 1商談</span><span>平均 30点</span></div></article>)}</div></section>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><p className="text-xs font-bold tracking-[0.15em] text-[#2563EB]">OODA</p><h2 className="mt-2 text-xl font-bold">営業アクション</h2><p className="mt-1 text-sm text-slate-500">活動状況、傾向、改善テーマ、次の対応を表示します。</p><div className="mt-6 grid gap-4 xl:grid-cols-2">{ooda.map(([number, title, entries]) => <article key={number} className="rounded-2xl border border-[#E5E7EB] p-5"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#2563EB] text-xs font-bold">{number}</span><h3 className="font-bold">{title}</h3></div><dl className="mt-5 divide-y divide-[#E5E7EB]">{entries.map(([label, value]) => <div key={label} className="grid gap-1 py-3 sm:grid-cols-[140px_1fr]"><dt className="text-xs font-bold text-slate-400">{label}</dt><dd className="text-sm font-bold text-slate-700">{value}</dd></div>)}</dl>{number === "04" && <div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => router.push("/selmo/roleplay")} className="rounded-lg bg-[#2563EB] px-3 py-2 text-xs font-bold">AIロープレ開始</button><button type="button" className="rounded-lg border border-[#DCE3ED] px-3 py-2 text-xs font-bold">関連ナレッジ確認</button><button type="button" onClick={() => router.push("/selmo/meetings")} className="rounded-lg border border-[#DCE3ED] px-3 py-2 text-xs font-bold">一覧を見る</button></div>}</article>)}</div></section>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><p className="text-xs font-bold tracking-[0.15em] text-[#2563EB]">SKILL</p><h2 className="mt-2 text-xl font-bold">スキル別評価</h2><p className="mt-1 text-sm text-slate-500">商談分析の評価項目をスキル別に表示します。</p><div className="mt-6 grid gap-3 lg:grid-cols-5">{skills.map(([label, description]) => <div key={label} className="rounded-xl border border-[#E5E7EB] p-4"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-bold">{label}</h3><span className="text-xl font-bold text-[#2563EB]">30</span></div><p className="mt-3 min-h-10 text-xs leading-5 text-slate-500">{description}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[30%] rounded-full bg-[#2563EB]" /></div></div>)}</div></section>

    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><p className="text-xs font-bold tracking-[0.15em] text-[#2563EB]">GROWTH</p><h2 className="mt-2 text-xl font-bold">成長推移</h2><p className="mt-1 text-sm text-slate-500">スコア、分析件数、ロープレ回数の推移を表示します。</p><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["AIスコア推移", "30点", "対象月平均"], ["成約率推移", "0%", "対象月"], ["分析件数", "1件", "対象月1件中"], ["ロープレ回数", "0回", "対象月"]].map(([label, value, note]) => <div key={label} className="rounded-xl bg-[#F8FAFC] p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p><p className="mt-2 text-xs text-slate-400">{note}</p><div className="mt-5 flex h-12 items-end gap-1">{[35, 48, 42, 60, 52, 70].map((height, index) => <span key={index} className="flex-1 rounded-t bg-yellow-300" style={{ height: `${height}%` }} />)}</div></div>)}</div></section>
  </div>;
}

function ListDemo({ rows, query, setQuery, onSelect, label }: { rows: Array<{ id: string; name: string; product: string; date: string; amount: number; status: string }>; query: string; setQuery: (value: string) => void; onSelect: (index: number) => void; label: string }) {
  return <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-[#E5E7EB] p-4 sm:flex-row"><div className="relative flex-1"><svg className="absolute left-3 top-3.5 h-5 w-5 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></svg><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`${label}を検索`} className="h-12 w-full rounded-xl border border-[#E5E7EB] bg-[#F8FAFC] pl-11 pr-4 text-sm outline-none focus:border-[#2563EB]" /></div><button onClick={() => alert(`${label}の登録フォームを開きます（デモ）`)} className="rounded-xl bg-[#2563EB] px-5 py-3 text-sm font-bold text-white">＋ 新規登録</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#F8FAFC] text-xs font-bold text-slate-500"><tr><th className="px-5 py-4">管理番号</th><th className="px-5 py-4">対象・顧客</th><th className="px-5 py-4">商品・内容</th><th className="px-5 py-4">日付</th><th className="px-5 py-4">金額</th><th className="px-5 py-4">状態</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((row, index) => <tr key={row.id} onClick={() => onSelect(index)} className="cursor-pointer hover:bg-blue-50/40"><td className="px-5 py-4 text-sm font-bold text-[#2563EB]">{row.id}</td><td className="px-5 py-4 text-sm font-bold">{row.name}</td><td className="px-5 py-4 text-sm text-slate-600">{row.product}</td><td className="px-5 py-4 text-sm text-slate-500">{row.date}</td><td className="px-5 py-4 text-sm font-bold">¥{row.amount.toLocaleString()}</td><td className="px-5 py-4"><StatusBadge tone={row.status === "完了" ? "green" : row.status === "確認待ち" ? "red" : "amber"}>{row.status}</StatusBadge></td></tr>)}</tbody></table></div></section>;
}

function FormDemo({ screen, message, setMessage }: { screen: DemoScreen; message: string; setMessage: (value: string) => void }) {
  return <div className="grid gap-6 xl:grid-cols-[1fr_340px]"><form onSubmit={(event) => { event.preventDefault(); setMessage(`${screen.label}をデモ登録しました`); }} className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="font-bold">基本情報</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">対象顧客<input required defaultValue="山田 花子" className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal outline-none focus:border-[#2563EB]" /></label><label className="text-sm font-bold">実施日<input required type="date" defaultValue="2026-08-05" className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal outline-none focus:border-[#2563EB]" /></label><label className="text-sm font-bold">商品・区分<select className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal"><option>有明牛乳 900ml</option><option>のむヨーグルト</option><option>その他</option></select></label><label className="text-sm font-bold">担当者<select className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal"><option>佐藤 美咲</option><option>田中 悠斗</option></select></label><label className="text-sm font-bold sm:col-span-2">備考<textarea className="mt-2 h-28 w-full rounded-xl border border-[#E5E7EB] p-4 font-normal" placeholder={`${screen.label}に関するメモ`} /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" className="rounded-xl border border-[#E5E7EB] px-5 py-3 text-sm font-bold text-slate-500">下書き保存</button><button className="rounded-xl bg-[#2563EB] px-5 py-3 text-sm font-bold text-white">登録する</button></div></form><aside className="rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><h2 className="font-bold text-blue-800">入力内容の確認</h2><p className="mt-3 text-sm leading-6 text-blue-700">この画面は操作確認用です。登録内容は外部へ送信されません。</p>{message && <div className="mt-5 rounded-xl bg-white p-4 text-sm font-bold text-emerald-700 shadow-sm">✓ {message}</div>}</aside></div>;
}

function ReportDemo({ screen, preview, setPreview, rows }: { screen: DemoScreen; preview: boolean; setPreview: (value: boolean) => void; rows: Array<{ id: string; name: string; product: string; date: string; amount: number; status: string }> }) {
  return <div className="space-y-6"><section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="font-bold">{screen.label}の出力条件</h2><div className="mt-5 grid gap-5 md:grid-cols-3"><label className="text-sm font-bold">対象日<input type="date" defaultValue="2026-08-05" className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal" /></label><label className="text-sm font-bold">コース<select className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal"><option>すべてのコース</option><option>Aコース</option><option>Bコース</option></select></label><label className="text-sm font-bold">出力順<select className="mt-2 h-12 w-full rounded-xl border border-[#E5E7EB] px-4 font-normal"><option>配送順</option><option>顧客番号順</option></select></label></div><div className="mt-5 flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" defaultChecked /> 電話番号を表示</label><label className="flex items-center gap-2"><input type="checkbox" defaultChecked /> 配送メモを表示</label><label className="flex items-center gap-2"><input type="checkbox" /> 休配を含む</label></div><div className="mt-6 flex justify-end gap-3"><button onClick={() => setPreview(true)} className="rounded-xl border border-[#2563EB] px-5 py-3 text-sm font-bold text-[#2563EB]">プレビュー</button><button onClick={() => window.print()} className="rounded-xl bg-[#2563EB] px-5 py-3 text-sm font-bold text-white">印刷・PDF</button></div></section>{preview && <section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{screen.label}</h2><p className="mt-1 text-xs text-slate-400">2026年8月5日・全コース</p></div><StatusBadge tone="blue">プレビュー</StatusBadge></div><table className="mt-5 w-full text-left text-sm"><thead className="border-y border-[#E5E7EB] bg-[#F8FAFC]"><tr><th className="p-3">No.</th><th className="p-3">顧客</th><th className="p-3">商品</th><th className="p-3">数量</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((row, index) => <tr key={row.id}><td className="p-3">{index + 1}</td><td className="p-3 font-bold">{row.name}</td><td className="p-3">{row.product}</td><td className="p-3">{index + 1}本</td></tr>)}</tbody></table></section>}</div>;
}

function AnalysisDemo({ screen }: { screen: DemoScreen }) {
  const values = [72, 88, 64, 93, 78];
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["対象件数", "1,284", "+4.2%"], ["当月実績", "¥5.08M", "+8.1%"], ["平均単価", "¥3,956", "+1.4%"], ["前月比較", "104.8%", "良好"]].map(([label, value, note]) => <div key={label} className="rounded-2xl border border-[#E5E7EB] bg-white p-5"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p><p className="mt-2 text-xs font-bold text-emerald-600">{note}</p></div>)}</div><section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">{screen.label}の推移</h2><p className="mt-1 text-xs text-slate-400">直近5か月のデモデータ</p></div><select className="rounded-lg border border-[#E5E7EB] px-3 py-2 text-xs font-bold"><option>月次</option><option>週次</option></select></div><div className="mt-8 flex h-64 items-end justify-around gap-4 border-b border-slate-200 px-4">{values.map((value, index) => <div key={value} className="flex h-full flex-1 flex-col justify-end"><div className="mb-2 text-center text-xs font-bold text-[#2563EB]">{value}</div><div className="rounded-t-lg bg-[#2563EB] transition-all" style={{ height: `${value}%` }} /><p className="mt-3 text-center text-xs text-slate-400">{index + 4}月</p></div>)}</div></section><section className="rounded-2xl border border-[#E5E7EB] bg-white p-6"><h2 className="font-bold">確認ポイント</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{["本社営業所が全体の61%を占めています", "前月より新規件数が8件増加しています", "金曜日の実績が最も高くなっています"].map((text) => <div key={text} className="rounded-xl bg-[#F8FAFC] p-4 text-sm leading-6 text-slate-600">{text}</div>)}</div></section></div>;
}

function StatusDemo({ screen, done, setDone }: { screen: DemoScreen; done: boolean; setDone: (value: boolean) => void }) {
  const steps = ["データ確認", "対象抽出", "処理実行", "結果確認"];
  return <div className="grid gap-6 xl:grid-cols-[1fr_340px]"><section className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-sm"><h2 className="font-bold">{screen.label}の処理状況</h2><div className="mt-6 space-y-3">{steps.map((step, index) => <div key={step} className="flex items-center gap-4 rounded-xl border border-[#E5E7EB] p-4"><span className={`flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold ${done || index < 2 ? "bg-emerald-100 text-emerald-700" : index === 2 ? "bg-blue-100 text-blue-700" : "bg-slate-100 text-slate-400"}`}>{done || index < 2 ? "✓" : index + 1}</span><div className="flex-1"><p className="text-sm font-bold">{step}</p><p className="mt-1 text-xs text-slate-400">{done || index < 2 ? "完了" : index === 2 ? "実行可能" : "待機中"}</p></div></div>)}</div></section><aside className="rounded-2xl border border-[#E5E7EB] bg-white p-6"><h2 className="font-bold">処理を実行</h2><p className="mt-3 text-sm leading-6 text-slate-500">デモでは実データを変更せず、処理完了までの流れを確認できます。</p><button onClick={() => setDone(true)} disabled={done} className="mt-6 w-full rounded-xl bg-[#2563EB] py-3 text-sm font-bold text-white disabled:bg-emerald-500">{done ? "✓ デモ処理完了" : "デモ処理を実行"}</button></aside></div>;
}
